warewulf/warewulf

- internal/app/wwctl/node/console/power.go
- internal/app/wwctl/node/console/root.go
- internal/app/wwctl/node/powercycle/power.go
- internal/app/wwctl/node/powercycle/root.go
- internal/app/wwctl/node/poweroff/power.go
- internal/app/wwctl/node/poweron/power.go
- internal/app/wwctl/node/root.go
- internal/app/wwctl/node/sensors/power.go
- internal/app/wwctl/node/sensors/root.go
- internal/pkg/batch/batch.go
- internal/pkg/power/ipmitool.go
- overlays/system/default/ipmi.ww
- test/batch-test.go
The batch stuff is pretty basic but does allow you to specify how many threads to run in parallel and for how long.  The idea is to issue say 50 IPMI poweron commands every 30 seconds.  I added a powercycle command a sensors command.  The IPMI sensors can be very slow on some servers.  I also added an IPMI console command.
> Added parallel batching, IPMI power cycle, sensors, and console

- internal/app/wwctl/node/powercycle/power.go
- internal/app/wwctl/node/poweroff/power.go
- internal/app/wwctl/node/poweron/power.go
- internal/app/wwctl/node/powerstatus/power.go
- internal/app/wwctl/node/sensors/power.go
- internal/pkg/batch/batch.go
- test/batch-test.go
Use a buffered channel to limit the number of active goroutines without needing
to wait for all active goroutines to finish
> Rework batch package

- etc/hosts.tmpl
- internal/app/wwctl/configure/hosts/main.go
- internal/pkg/util/util.go
Here are the changes in this PR.
1. Make a backup (/etc/hosts.wwbackup) the first time we configure the local /etc/hosts file on the warewulf server.
2. Put all of our changes in the local /etc/hosts file after the comment line:
The local admin can make local changes to the /etc/hosts file as long as he edits the file above the comment line.
> Back up /etc/hosts and allow local changes

- internal/app/wwctl/container/imprt/main.go
- internal/pkg/container/pull.go
- internal/pkg/oci/puller.go
Adds support to 3 environment variables:
- WAREWULF_OCI_USERNAME: registry user username
- WAREWULF_OCI_PASSWORD: registry user password
- WAREWULF_OCI_NOHTTPS: disable tls requirements (for local registries)
Note:
This will default to ~/.docker/config.json for credentials and other docke configurations on the system when no options are specified.
Note^2: this should be merged after #26
>  Support OCI registry creds with environment variables

- internal/app/wwctl/node/delete/main.go
- internal/app/wwctl/node/delete/root.go
- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/profile/delete/main.go
- internal/app/wwctl/profile/delete/root.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/profile/set/root.go
Adds `if SetYes == true` logic to `wwctl profile set...`, `wwctl profile delete...` and `wwctl node delete...` commands and ensures `warewulfd` is reloaded after `wwctl {node,profile} set...` commands to resolve issues reported in #56.
There are other `wwctl` commands which call `nodeDB.Persist()` and do not include `warewulfd.DaemonReload()`. Not sure if those should also be modified so I didn't touch them.
> Add --yes option to some profile and node commands and ensure warewulfd is reloaded

- internal/app/wwctl/overlay/edit/main.go
- internal/pkg/overlay/overlay.go
changed `GroupName` to `ClusterName`.
Now `wwctl node set -c <clustername>` can be used on overlays.
> GroupName --> ClusterName

- internal/app/wwctl/node/list/main.go
- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/profile/list/main.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/node/constructors.go
- internal/pkg/node/datastructure.go
- internal/pkg/node/modifiers.go
- internal/pkg/overlay/overlay.go
Feature to add custom parameters to the node configuration and profiles.
It's intended to increase the flexibility of the config.
I allows for instance to import profile-specific files.
```
wwctl profile set -p dummy --value "/var/warewulf/opt/dummyImportProfile.txt" default
```
by using
```
{{Include (printf "%v" $.Params.dummy)}}
```
in a foobar.ww overlay-template, the `dummy` parameter is resolved and the respective file is imported.
As `dummy` is can be specified in the profile, a generic overlay can be used and files can still be managed by profiles.
> custom Parameters

- Makefile
- By using the module mirror, we get around the issue of using an older
git client such as that which comes with CentOS 7.
- Using a module mirror helps to speed up module downloads.
Fixes #89
> Use Module Mirror For Downloads

- internal/pkg/node/datastructure.go
- internal/pkg/overlay/overlay.go
- overlays/system/default/etc/wicked/ifconfig/ifcfg-eth0.xml.ww
It is possible to configure wicked (the SUSE network daemon) via xml files in `/etc/wicked/ifconfig/ifcg-$NAME.xml`, so a SUSE and EL like network configuration can coexist without having issues with `/etc/sysconfig/network`. This PR addes this files and also modifications in the node code, as the xml files needs the CIDR notation as is has not neimask option.
This is an alternative to #83
> Wicked integration into default overlay

- internal/pkg/node/constructors.go
- internal/pkg/node/methods.go
Minor fixup so the `--discoverable` feature for nodes actually works.
> Discoverable fix

- internal/app/wwctl/profile/list/main.go
We added the ability to configure an IPMI interface. We missed
displaying the configuration when listing all profiles.
> Show IPMI Interface When Listing All Profiles

- internal/pkg/overlay/overlay.go
- internal/pkg/util/util.go
Overlay generation was failing silently due to chmod matching on a target which doesn't exist -- Template files are renamed from `path.ww` -> `path` and thus would cause an error on the `filepath.Walk()`.
> Overlay Fixup

- internal/app/wwctl/container/exec/child/main.go
Hoping this fixes what @mslacken found on SLES Leap with regards to mounts not going away when the mount namespace shuts down.
> MS_REC added to MS_PRIVATE mount on root

- internal/app/wwctl/overlay/chmod/main.go
- internal/app/wwctl/overlay/chmod/root.go
- internal/app/wwctl/overlay/chown/main.go
- internal/app/wwctl/overlay/chown/root.go
- internal/app/wwctl/overlay/root.go
- internal/pkg/util/util.go
Now that we have the appropriate backend to handle overlay file ownership, this PR adds a frontend command to change ownership on files and directories.
> Added overlay chown subcommand

- Makefile
Its not practical to run `make clean ; make` every time you want to
rebuild one of the go binaries. Go will automatically cache builds and
file changes.
> Always rebuild the go binaries

- cmd/wwctl/main.go
- internal/app/wwctl/node/add/main.go
- internal/app/wwctl/root.go
Better error handling, use less `os.Exit()`, and more error returns. Also prints a stack trace for `wwctl` if
`--debug` flag is used.
Example: 
```console
$ ./wwctl node add foo # no debug flag
[ERROR] 	  2021/09/10 11:56:52 Could not create new configuration file: open /etc/warewulf/nodes.conf: no such file or directory
[ERROR] 	  2021/09/10 11:56:52 Configuration file not found: /etc/warewulf/warewulf.conf
error reading node configuration file
Error: failed to open node database: open /etc/warewulf/nodes.conf: no such file or directory
./wwctl: failed to open node database: open /etc/warewulf/nodes.conf: no such file or directory
$ ./wwctl -d node add foo # with debug flag
[ERROR] 	  2021/09/10 11:56:55 Could not create new configuration file: open /etc/warewulf/nodes.conf: no such file …
```
> Better error handling for some of wwctl commands

- cmd/wwctl/main.go
- internal/app/wwctl/node/list/main.go
- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/overlay/build/main.go
- internal/app/wwctl/overlay/build/root.go
- internal/app/wwctl/overlay/chmod/main.go
- internal/app/wwctl/overlay/chmod/root.go
- internal/app/wwctl/overlay/chown/main.go
- internal/app/wwctl/overlay/chown/root.go
- internal/app/wwctl/overlay/create/main.go
- internal/app/wwctl/overlay/create/root.go
- internal/app/wwctl/overlay/delete/main.go
- internal/app/wwctl/overlay/delete/root.go
- internal/app/wwctl/overlay/edit/main.go
- internal/app/wwctl/overlay/edit/root.go
- internal/app/wwctl/overlay/imprt/main.go
- internal/app/wwctl/overlay/imprt/root.go
- internal/app/wwctl/overlay/list/main.go
- internal/app/wwctl/overlay/list/root.go
- internal/app/wwctl/overlay/mkdir/main.go
- internal/app/wwctl/overlay/mkdir/root.go
- internal/app/wwctl/overlay/show/main.go
- internal/app/wwctl/overlay/show/root.go
- internal/app/wwctl/profile/list/main.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/root.go
- internal/pkg/node/constructors.go
- internal/pkg/overlay/overlay.go
These updates (still in testing) change how overlays are addressed by putting `system` or `runtime` as a mandatory option on the CLI.
Please test.
> Overlay UI updates

- Makefile
This is a minor fix to ensure that Warewulf can be built from the `make dist` tarball offline.
> Vendor make fix

- internal/app/wwctl/container/exec/root.go
'container exec' command.
Update documentation for the 'container exec' command.
> Fix panic when failing to include the command to be run by the

- internal/pkg/warewulfd/warewulfd.go
in line 42 of warewulfd.go, the port number was hard coded.
> Fixes #135

- internal/pkg/kernel/kernel.go
> allow compressed kernels with gz suffix

- include/systemd/warewulfd.service
- warewulf.spec.in
These commits do the following:
- Fix package reference for EL7
- Update spec file to use systemd macros
- Use macros to refer to file paths
- Update syntax
- Fix link to documentation in systemd unit file
> Update spec file and systemd unit file

- internal/app/wwctl/container/build/root.go
- internal/app/wwctl/container/delete/root.go
- internal/app/wwctl/container/exec/root.go
- internal/app/wwctl/kernel/delete/root.go
- internal/app/wwctl/kernel/imprt/root.go
- internal/app/wwctl/node/delete/root.go
- internal/app/wwctl/node/ready/root.go
- internal/app/wwctl/node/sensors/root.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/overlay/list/root.go
- internal/app/wwctl/power/off/root.go
- internal/app/wwctl/power/on/root.go
- internal/app/wwctl/power/reset/root.go
- internal/app/wwctl/power/soft/root.go
- internal/app/wwctl/power/status/root.go
- internal/app/wwctl/profile/set/root.go
Adds dynamic nouns, so that e.g.
```
wwctl kernel delete <TAB><TAB>
```
will give you a list of the installed kernels. Works now for various subcommands.
> Bash-completion dynamic nouns

- Makefile
- etc/nodes.conf
- internal/app/wwctl/overlay/build/root.go
- internal/app/wwctl/overlay/chmod/root.go
- internal/app/wwctl/overlay/chown/root.go
- internal/app/wwctl/overlay/create/root.go
- internal/app/wwctl/overlay/delete/root.go
- internal/app/wwctl/overlay/edit/root.go
- internal/app/wwctl/overlay/imprt/root.go
- internal/app/wwctl/overlay/list/root.go
- internal/app/wwctl/overlay/mkdir/root.go
- internal/app/wwctl/overlay/show/root.go
- internal/app/wwctl/power/cycle/root.go
- internal/app/wwctl/profile/add/root.go
- internal/app/wwctl/profile/delete/root.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/node/datastructure.go
- warewulf.spec.in
These changes allow RPMs to build without errors or unwanted behavior.
- The GT/LT signs in help were simply swapped for parentheses to avoid the man page errors. The user output is correct now.
- Automatic node.conf generation was removed and replaced with a warning. It's nice to have autocreation, but it shouldn't be triggered when node information isn't needed. RPM assembly is done in BUILD subdirectory, yet before this patch, simply using go functions under pkg would trigger nodefile generation in system /etc.
- Man and bash completion generation were moved to %build. New content shouldn't be generated in %install; this is important when debugging rpmbuild.
- Lots of other changes to the specfile.
> Patch for RPM builds

- Makefile
- internal/pkg/node/constructors.go
- internal/pkg/node/util.go
- internal/pkg/node/util_test.go
fixes #198 
added `early fail` for FindByHwaddr and FindByIpaddr to catch non-MAC and non-IP strings as early as possible
> fix FindByHwaddr

- internal/pkg/node/methods.go
regexp.MatchString will match also substrings, what means that 
```
wwctl node list node1
```
will not only match `node1` but also `node10`, so its impossible to target `node1` which is also described in #203.
With '^' at start of the search string and '$' at the end, its possible to target `node1`. The old behavior can be retained with
```
wwctl node list node1.
```
> Adding '^' and '$' to serach string to avoid greedy regexp

- internal/pkg/warewulfd/ipxe.go
Adding two fields to make available to iPxe templates.
- Id : Already there as hostname and fqdn, adding ID to be consistent with node field naming. 
- Cluster: Adding for consistency
The motivation here is to pass values in as kernel params to avoid the need to write files into the image via overlays for trivial node/asset information and to make all values available to the iPxe templates that are available to overlay templates.
These two commits could be folded together, but I didn't know how to do that offhand.
> Add fields for use in iPxe templates

- .github/workflows/releasebuild.yml
- Makefile
- ci/mockbuild.sh
- warewulf.spec.in
When a new release is published, the GH workflow will:
- Build the distribution tarball
- Use the tarball to build el7 and el8 RPMS using mock on Rocky Linux
- Upload the tarball and RPMs to the release
> Add GitHub action to build new release assets and upload them

- internal/app/wwctl/container/imprt/root.go
> Fix misspelled export command for wwctl container

- internal/app/wwctl/node/console/power.go
- internal/app/wwctl/node/list/main.go
- internal/app/wwctl/profile/list/main.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/profile/set/root.go
- Fix the logs to reference the correct IPMI setting that is being set.
- Add setting the IPMI port at a profile level.
- Apply all IPMI settings when preparing to us the console.
Closes #225
> ipmi: Fix log output, set IMPI port on profile and settings for console

- go.mod
- go.sum
- internal/app/wwctl/configure/nfs/main.go
- internal/pkg/warewulfconf/datastructure.go
This fixes the bug where wwctl ignores the `enabled` option from `/etc/warewulf/warewulf.conf`, and also adds a new `NfsExtended` namespace to expose configuration of NFS mount options and static-fstab mounts.
Refs #183
> Some improvements for handling NFS mounts

- internal/pkg/util/util.go
`wwctl container exec` doesn't detect file owner/permission change when exit and decide not to build VNFS(https://github.com/hpcng/warewulf/issues/193).
This request implemented to use 'ctime' instead of 'mtime' to detect owner/permission changes.
> use ctime instead of mtime to detect file owner/permission change

- internal/pkg/node/methods.go
Minor fix-up to cleanup search query so duplicate node entries don't show up multiple times:
```
$ sudo wwctl node list n0000 n0000
NODE NAME              PROFILES                   NETWORK
================================================================================
n0000                  default                    eth0:192.168.1.1
n0000                  default                    eth0:192.168.1.1
```
Vs.
```
$ sudo ./wwctl node list n0000 n0000
NODE NAME              PROFILES                   NETWORK
================================================================================
n0000                  default                    eth0:192.168.1.1
```
> Optimized FilterByName() to weed out redundant queries

- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/node/constructors.go
This allows backwards compatibility for node configurations that do not specify the network's device name (previously was the netdev member ID).
> Backwards compatibility fix for network config

- .gitignore
- Makefile
- cmd/config_defaults/config_defaults.go
- etc/warewulf.conf.in
- internal/app/wwctl/configure/nfs/main.go
- internal/app/wwctl/node/ready/main.go
- internal/app/wwctl/overlay/list/main.go
- internal/pkg/container/imprt.go
- internal/pkg/container/util.go
- internal/pkg/kernel/kernel.go
- internal/pkg/oci/cache.go
- internal/pkg/oci/defaults.go
- internal/pkg/overlay/config.go
- internal/pkg/overlay/overlay.go
- internal/pkg/warewulfconf/constructors.go
- internal/pkg/warewulfconf/datastructure.go
- internal/pkg/warewulfconf/defaults.go
- internal/pkg/warewulfconf/modifiers.go
- warewulf.spec.in
This change provides the ability to set the default directory for server files, in addition to changing the active location using the warewulf.conf file. In addition, the default location is moved from /var/warewulf to /srv/warewulf, to strictly adhere to the Linux FHS which generally prohibits new directories directly under /var.
The default locations for both Warewulf server files and TFTP IPXE files are set during make through variables. The currently hardcoded "/warewulf" subdirectory name has not been made configurable in this update.
One nice result is that any missing fields in warewulf.conf now use default values. The IP and netmask are still needed. If those are missing, the warning was changed to an error, because without these fields wwctl will crash.
My understanding of Golang …
> Support for relocatable Warewulf server file share

- internal/pkg/kernel/kernel.go
Minor fix up of `path.Join()` syntax referring to comment in #241.
> Minor fix of path.Join() usage

- internal/app/wwctl/configure/ssh/main.go
Signed-off-by: Christian Goll <cgoll@suse.de>
> removed leading /etc for key location

- internal/app/wwctl/configure/dhcp/dhcp_main_test.go
- internal/app/wwctl/configure/dhcp/main.go
This is a single character bug fix.
Broke this out into a function for testing.
> Missing hyphen in dhcp template path. Unit tests.

- internal/app/wwctl/container/build/build_test.go
- internal/app/wwctl/container/build/root.go
We didn't need to add an arg check here because it's already there.
> Fix container build --all. #215.

- internal/app/wwctl/overlay/chmod/chmod_test.go
- internal/app/wwctl/overlay/chmod/main.go
Tested manually by: sudo wwctl overlay chmod wwinit /warewulf/wwinit 755
Considering how to automate such testing. It may require a make install on the build machine, and I need to find out more about how that works.
> Fix wwctl chmod arg parsing.

- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/exec/root.go
Adds `/usr/bin/bash` as default argument for
`wwctl container exec foo`
> will exec /usr/bin/bash if no cmd is provided

- internal/pkg/container/build.go
Usage of this feature is very basic, but an example exlucde file would be
```
/boot/
./var/cache
./usr/src
```
with `./FOO` refering to FOO in the rootfs of the container.
As `wwctld -dv container build FOO` will show the exact command, the 'source' of exclude 
is exhibited to the admin.
> heck if ./.ww4/exludes exist and use if its exists

- internal/app/wwctl/container/root.go
- internal/app/wwctl/container/show/main.go
- internal/app/wwctl/container/show/root.go
Adds the command `wwctl container show $FOO` what will show the 
rootfs for the container $FOO. The `-a` option is also provided
to give more info.
> container info

- internal/pkg/container/build.go
- the exclude file is now under $ROOTFS/etc/warewulf/exclude
- find will not descent into other filesystemd or automount as
this avoids accidents with bind mounts
> moved exclude file location and find -xdev 

- etc/hosts.tmpl
For hosts with ip addresses, the hosts file entry should be:
```
<ip> <node_name> <node_name>-<network_device>
```
I have a fix for this here. Manual testing with the command below gives me the result below. I'm not immediately sure of a great way to test this because it would modify /etc/hosts. Sounds like I need to understand CI more.
I had to manually copy in the template file because the makefile install does not clobber it. 
Installation:
```
[mhink@localhost warewulf]$ pwd
/home/mhink/go/src/github.com/hpcng/warewulf
sudo cp etc/hosts.tmpl /usr/local/etc/warewulf/hosts.tmpl
sudo chmod 644 /usr/local/etc/warewulf/hosts.tmpl
```
Configuration:
```
[mhink@localhost warewulf]$ sudo wwctl configure hosts
[mhink@localhost warewulf]$ cat /etc/hosts
127.0.0.1   localhost …
```
> Fix network name in /etc/hosts. Fixes #247.

- internal/app/wwctl/configure/nfs/main.go
- internal/pkg/overlay/overlay.go
- overlays/wwinit/etc/fstab.ww
the file `/etc/fstab` created with `wwctl configure nfs` takes bits which are baked into wwctl. Having the file as a template `fstab.ww` allows some flexibilty for other mounts.
> moved fstab creation for nodes to template

- internal/app/wwctl/kernel/imprt/main.go
- internal/app/wwctl/kernel/imprt/root.go
- internal/pkg/kernel/kernel.go
With the `-D` flag a kernel can now be detected under the directories provided by kernelSearchPaths.
This detection needs either container via the `-C` option or a chroot via the `--root` option to work.
> added option for automatic kernel detection

- internal/pkg/kernel/kernel.go
Due to the nature of provisioning nodes when there are symbolic
links involved we want to copy the file that they point to instead
of copying the link.
Backporting change from 4.2.x branch
Issue #281
> Add dereference option when importing the kernel.

- Makefile
- internal/app/wwclient/root.go
- internal/pkg/buildconfig/defaults.go
- internal/pkg/buildconfig/setconfigs.go.in
`wwclient` checks in what location the binaries it is, and won't 
execute correctly if it is the wrong. This was introduced, to have a
`wwctl` and `wwclient` to be same the binary, but is quite a good 'security` 
againts fat fingered admins, not to accidently overwrite the '/'-dir 
of the ww4 master node. 
So this patch makes the location of `wwclient` configureable with a 
single source of truth.
Should fix #284.
> make location of buildconf

- internal/app/wwctl/configure/dhcp/dhcp_main_test.go
Test needs to pass on non-default configurations.
> Fix hardcoded path in test. Use the configuration setting.

- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/profile/set/root.go
When no profile is selected, assume `default`, and when node nodes are selected, assume all, but also emit a giant warning.
> Setting sane defaults for node and profile selection

- internal/app/wwctl/container/exec/child/main.go
After exiting a shell with `wwctl container exec` a script/executeable `./.ww4/runExit`
will be executed.
> execute './.ww4/runExit` on exit of container exec

- internal/pkg/overlay/overlay.go
`tstruct.Keys` is currently uninitialised, leading to panics when custom keyvalue pairs are used.
> Initialise Keys map for overlay templates

- internal/app/wwctl/container/exec/child/main.go
- internal/app/wwctl/container/exec/main.go
This is a different implementation for the runner in #271 that executes the `container_exit.sh` script when the container exits.
> Container exit script runner

- internal/pkg/util/copyfile.go
ioCopy(destination,source) is not like standard unix cp. Fixed this
> fixed syntax for io.Copy

- Makefile
This PR fix #344 
`$(DESTDIR)$(WWDATADIR)/ipxe` was file.
This cause a problem when copying *.efi files to `$(DESTDIR)$(WWDATADIR)/ipxe`.
This commit makes `$(DESTDIR)$(WWDATADIR)/ipxe` to be directory from file.
> makes `$(DESTDIR)$(WWDATADIR)/ipxe` to be directory from file

- internal/app/wwctl/overlay/build/main.go
- internal/pkg/configure/dhcp.go
- internal/pkg/configure/nfs.go
- internal/pkg/warewulfconf/datastructure.go
- internal/pkg/warewulfconf/defaults.go
Adds the bool option 
warewulf:
host overlay: true
so that host overlays can be disabled. The command 
`wwctl build overlay -H` will still build the host overlay, as
this may be explicitly wanted.
> warewulf.conf option disable host overlays

- Makefile
- internal/pkg/overlay/overlay.go
- internal/pkg/wwlog/wwlog.go
If there is a user writeable file in the host overlay, a user can
create arbitrary files on the host root file system. Although these
files will belong to this user, this might allow users to modify
any files.
So this patch restricts the access to the host overlay to root and
produces a warning if this was changed.
> use secure overlay dir

- internal/pkg/node/constructors.go
When set, node HW addresses are converted to lowercase. It doesn't affect unmarshalling.
> Fix uppercase MAC error

- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/node/datastructure.go
- internal/pkg/node/methods.go
Fixes issues #395, #391, and #392 
- Updates the netdel argument to use the network name instead of the network device, which caused the command to fail.
- Enables an option to set the default network in a profile.
- Fixes the boolean set method in the node datastructure. Previously, a false value would do nothing, so a "true" value couldn't be unset
- Changes the main network device identifier from "default" to "primary". Default is defined as fallback or failover, so term was used incorrectly here (in addition to being overloaded).
> Fix wwctl bug deleting networks and ability to set default network

- Makefile
- internal/app/wwctl/version/main.go
- internal/app/wwctl/version/root.go
`wwctl version` will print out all complied in vars. This will make debugging for users much easier, e.g #394
> more verbose wwctl version

- internal/app/wwctl/container/show/main.go
The `wwctl container show -a` command should also list the actual kernel of a container.
> container show prints kernel version

- etc/warewulf.conf
Update the default warewulf.conf file, so that working /opt mount arguments are supplied.
> Fix /opt defaults in warewulf.conf

- internal/pkg/container/build.go
This feature never ran because it was looking for the wrong file. All other Warewulf code uses the plural "excludes".
> Fix container excludes

- internal/pkg/overlay/datastructure.go
- internal/pkg/overlay/overlay.go
The split function allows the creation of string slices in templates out of a string. This is extremly useful, as the `range` expression in tempaltes only works with slices and maps. With this function following is possible:
```
{{ $devices := split .Tags.devices ";" -}}
{{ range $dev := $devices -}}
Do stuff with {{ $dev }}
{{  end }}
```
and store the devices in the central configuration as `;` seperated list.
Simple full disk deployments can so be enabled without the need if having addiotnal variables in the configuration.
> updated overlay includes more vars and split func

- cmd/update_configuration/update_configuration.go
- cmd/update_configuration/vers43/datastructure.go
- internal/app/wwctl/node/list/main.go
- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/profile/list/main.go
- internal/app/wwctl/profile/set/main.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/node/constructors.go
- internal/pkg/node/datastructure.go
- internal/pkg/node/modifiers.go
- internal/pkg/overlay/overlay.go
- overlays/host/etc/dhcp/dhcpd.conf.ww
- overlays/host/etc/hosts.ww
- overlays/wwinit/etc/systemd/network/10-persistent-net.link.ww
Within netdev structs, Default is renamed to Primary. Cobra commander variables using "default" for the primary network are also renamed.
> Renames instances of "Default" to "Primary" in netdev source code

- internal/app/wwctl/overlay/build/main.go
- internal/pkg/util/util.go
If a overlay should be build, check if the overlay is assigned to
a node, and return error if otherwise.
Adresses #399
> only build assigned overlays

- overlays/generic/etc/hosts.ww
- overlays/host/etc/hosts.ww
Looks like a typo in the overlay file. Needs to have a space after the dash or parsing the template fails.
> Fix hosts error

- ci/mockbuild.sh
This PR is fix CI build release.
New mock need explicit config file.
Rocky 7 not available use centos-7 instead.
> Fix CI build release

- etc/ipxe/default.ipxe
- internal/pkg/warewulfd/util.go
DO NOT MERGE YET!
A minor fix/workaround to always use compression for what Norm Gaywood found in Slack with regards to the compute nodes running out of memory while trying to fetch the container images.
Also, I included an optimization in the `sendFile()` function to not load full binary data blobs into memory before sending over the the HTTP writer as doing that in parallel would kill a control server.
note: We might decide a different/better fix for the first issue and I'd like validation on the second.
> 4.3.0rc6 fixes

- internal/pkg/configure/tftp.go
fix issue #319 
We meet three situations in tftp enable config.
1. do nothing(don't mkdir and copy files).
2. prepare dir and copy files to tftproot path.
3. do step 2 and more with start service, enable service
boolean cannot handle theses.
In this fix 'enable' only decide whether we start service.
> can disable tftp services with warewulf.conf

- internal/app/wwctl/root.go
- internal/app/wwctl/ssh/main.go
- internal/app/wwctl/ssh/root.go
Support the ability to spawn parallel ssh commands to nodes from the control server.
```
$ ./wwctl ssh --fanout 64 .*cluster hostname
n0001.cluster: Default network IP address not configured
n0000.cluster: n0000.cluster
```
> Add feature to use wwctl to spawn ssh commands

- internal/app/wwctl/overlay/build/main.go
- internal/app/wwctl/overlay/build/root.go
- internal/app/wwctl/overlay/imprt/main.go
- internal/pkg/overlay/overlay.go
- internal/pkg/util/util.go
- internal/pkg/warewulfd/nodedb.go
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/util.go
Fixes
* Thread safety of configuring discoverable nodes and overlay builds
* Update to `wwctl overlay build` command in handling of lists of overlay names.
> Fix server thread safety of discoverable node and overlay build

- etc/ipxe/default.ipxe
GitHub PR #235 adds an advanced boot mechanism for UEFI machines which
causes old Legacy BIOS nodes to hit the 3 GB RAM barrier in 32 Bit iPXE
very quickly. Therefore, detect if an EFI or Legacy BIOS is loaded and
fall back to the old boot path in the second case.
This PR fixes GitHub issue #497.
> Fix the boot process for Legacy BIOS machines

- internal/pkg/power/ipmitool.go
Historically, warewulf IPMI commands output extraneous newlines, producing output like this:
```
$ sudo wwctl power status c[1-4].dell-ciq.lan
c2.dell-ciq.lan: Chassis Power is on
c4.dell-ciq.lan: Chassis Power is on
c3.dell-ciq.lan: Chassis Power is on
c1.dell-ciq.lan: Chassis Power is on
```
This change trims extraneous whitespace, leading to output like this:
```
$ sudo wwctl power status c[1-4].dell-ciq.lan
c2.dell-ciq.lan: Chassis Power is on
c4.dell-ciq.lan: Chassis Power is on
c3.dell-ciq.lan: Chassis Power is on
c1.dell-ciq.lan: Chassis Power is on
```
This makes the output more like the output from `wwctl ssh` and other similar tools, improves readability, and better supports use with `dshbak`.
> Trim whitespace from IPMI output

- warewulf.spec.in
Naive implementation; but without some declaration rpmbuild fails.
> Capture wwapi binaries in rpm spec

- containers/Docker/rocky-8
Without the kernel-modules package installed I was not able to use apptainer, as squashfs was not available.
Porting this in from https://github.com/anderbubble/warewulf/pull/2, where I had accidentally created it before.
> Install kernel-modules in warewulf rocky-8 image

- internal/pkg/container/syncuids.go
I think the `.` in `uid./gid not synced` is erroneous.
Ported from https://github.com/anderbubble/warewulf/pull/1
> Removed extra period from log message

- CHANGELOG.md
- internal/app/wwctl/overlay/chown/main.go
Specifying 0 for gid as a default during chown causes the gid to be changed to 0 when left unspecified. Changing the default value to -1 causes the gid to be left unmodified when unspecified, which is a less surprising behavior.
> Don't change unspecified gid to 0 during chown

- CHANGELOG.md
- internal/app/wwctl/overlay/chown/main.go
It appears that the intended behavior of overlay chown was changed in 00d8d42e9, but the argument handling was not updated to reflect the removal of overlayKind. This led to a crash when only the uid was specified, and a processing of the gid as the uid otherwise.
Fixes #486 
> Fix handling of uid and gid arguments during chown

- internal/app/wwctl/container/show/main.go
- internal/pkg/api/container/container.go
Commit d8cd6049 introduced erroneous output coming from an inner function of container show, and (seemingly) erroneously replaces valid kernel versions with "not found". This commit fixes both of those issues, and moves the output to the outer cli function.
> Fix output of wwctl container show

- internal/pkg/util/copyfile.go
- overlays/host/etc/profile.d/ssh_setup.csh
- overlays/host/etc/profile.d/ssh_setup.sh
The `exit` statement in `overlay/host/etc/profile.d/ssh_setup.*sh` prevents system user from logging in. Instead, `if` based script is safe under both sourced and execed scenario.
The second commit fixes that destination file is not properly truncated when building the overlay. This can be easily tested with adding `#test` to `/etc/profile.d/ssh_setup.sh` and `#-` to `overlay/host/etc/profile.d/ssh_setup.sh`. Then run `wwctl overlay build -H` and check if the last line in `/etc/profile.d/ssh_setup.sh` becoms `#-est`
> remove exit from ssh_setup.*sh

- internal/app/wwctl/ssh/main.go
`wwctl ssh` has the "default" network interface hardcoded. Use the interface with the primary field instead.
@anderbubble can you please review
> Use primary netdev for ssh

- CHANGELOG.md
- internal/pkg/container/build.go
- internal/pkg/util/util.go
This PR fixes the handling of the `/etc/warewulf/excludes` file read from the container definition, and further excludes files that reside in an excluded directory. (This functionality is otherwise missing due to deficiencies in `filepath.Match`. See https://github.com/golang/go/issues/11862)
This PR also largely rewrites `FindFilterFiles` in an attempt to prevent such errors in the future.
This is a rather significant rewrite of an integral function, and likely merits close review by senior developers / maintainers. However, it also includes a fix for a significant functional regression, so I suggest that it also merits priority.
Fixes #532
> Fix of container build include/exclude handling

- include/systemd/warewulfd.service.in
We discussed this a while back and I volunteered to look into it, but I didn't expect it to be this easy to do. Putting in this PR in case this is the right thing, but I have a faint recollection we discussed changing how warewulfd is started so that logs would go to stdout/stderr and get picked up by `systemd`?
> Add execreload and execstop to warewulfd.service.

- .github/workflows/documentation.yml
If a fork is running GH actions, do not create the static documentation and try to push to the warewulf documentation repo.
Signed-off-by: Michael L. Young <myoung@ciq.co>
> [CI/CD] Check owner of repo before running documentaton GH action

- Makefile
- warewulf.spec.in
Needed to support OBS.
Also adds dependencies to support new go modules.
Tested on Rocky 8.
> Add support for offline builds

- internal/pkg/overlay/datastructure.go
NodeConf.Tags doesn't get initialized and panics when building an overlay that has a .ww template file for a node which has tags set.
> Fix use of uninitialised Tags map

- internal/pkg/configure/hostfile.go
- internal/pkg/overlay/overlay.go
wwctl configure hostfile was using the /host/ path twice, causing it to look in the wrong place for /etc/hosts.ww
Fixes #571 
> Correct host overlay processing during configure

- internal/app/wwctl/container/shell/main.go
Set environment variable `WW_CONTAINER_SHELL` to the name of the container when a user shells into it via command `wwctl container shell ...`. 
Resolves #574
> Env var to identify when in container shell

- internal/pkg/util/util.go
The current internal/pkg/util `FileGz()` function properly locates the `pigz` command path using `exec.LookPath()`.  If that command is unavailable, then an info message is emitted and the function uses the string `"gzip"` as the command.  The `--keep` flag is presented to `gzip` to prevent removal of the uncompressed file after successful compression.  But older versions of `gzip` (for example, on CentOS 7) do not grok that flag:
```
:
Rebuilding container...
INFO   : Created image for VNFS container rocky-8.6: /opt/warewulf/4.3.0/srv/warewulf/container/rocky-8.6.img
VERBOSE: Could not locate PIGZ
VERBOSE: Using gz compressor: gzip
ERROR  : Could not build container rocky-8.6: Failed to compress image for VNFS container rocky-8.6: …
```
> VNFS gzip:  fallback to redirected stdout

- Makefile
Makefile was checking WWCONFIGDIR in some places. In others it was duplicating the explicit paths that make up WWCONFIGDIR. Here, update all such references to always use the WWCONFIGDIR macro.
> Use WWCONFIGDIR for all relevant install paths

- internal/pkg/node/constructors.go
Why have I done this?
- Because defaults.conf had a starting newline, which bugs me.
- Because moving the first line of FallBackConf looks unlovely.
- Because yaml happens to have a --- document-start syntax.
I completely agree that this is (hopefully) a no-op change; but if anyone else thinks it makes things aesthetically more pleasing, and agrees that it doesn't break anything, go ahead and merge. ^_^
> Add --- to the head of FallBackConf

- CHANGELOG.md
- internal/pkg/overlay/overlay.go
`os.MkdirAll(path.Join(outputDir, location), info.Mode())` respects the set umask, so any write group/other write permissions on directories within an overlay currently get discarded.
Fix:
Set the umask to `0000` only while building overlays.
- Fixes #584
> Set umask to 0000 while overlays are being built. Fixes #584

- internal/pkg/overlay/datastructure.go
Commenter in #627 noticed that a set of initialization lines were repeated twice. This PR removes the redundant set.
> Remove redundant code

- internal/pkg/oci/puller.go
cosigned images can't be imported all time, so enforce to remove the signature
> remove signature from OCI image

- CHANGELOG.md
- internal/app/wwctl/overlay/list/main.go
Causes the correct header to be displayed when both `-a` and `-l` flags are used together.
- Fixes #485
> Correct header for overlay list -al

- overlays/debug/warewulf/template-variables.md.ww
Fixes a bug in the debug template that was causing the next node to be printed on the same line as the last line of the previous node.
Previously:
```yaml
- AllNodes[0]:
- Id: asdf1
[...]
- Tags: - AllNodes[1]:
- Id: n1
```
Now:
```yaml
- AllNodes[0]:
- Id: asdf1
[...]
- Tags: 
- AllNodes[1]:
- Id: n1
```
> Fix newline when printing AllNodes

- .github/workflows/documentation.yml
- .github/workflows/lint.yaml
The previous CI configuration didn't build docs, and didn't try to build docs for PRs. Linting was also skipped for pushes to development. This PR updates the scenarios in which docs are built and tests are run.
> Update GitHub CI to build docs and lint

- CHANGELOG.md
- overlays/generic/etc/hosts.ww
- overlays/host/etc/hosts.ww
The hosts file man page (`man hosts`) states:
> This file is a simple text file that associates IP addresses with
> hostnames, one line per IP address.  For each host a single line should
> be present with the following information:
>
>     IP_address canonical_hostname [aliases...]
As such, it seems that the hostname should be first in the list.
This is particularly true for the `warewulf` alias for the server itself, which is certainly an alias for the canonical hostname.
> Emit canonical hostnames first

- internal/pkg/buildconfig/defaults.go
- internal/pkg/configure/tftp.go
- internal/pkg/overlay/datastructure.go
- internal/pkg/warewulfconf/constructors.go
- internal/pkg/warewulfconf/datastructure.go
- overlays/host/etc/dhcp/dhcpd.conf.ww
The location and file names of the ipxe binaries are hardcoded. So this change makes them configurable via `warewulf.conf`.
> make ipxe binary source configurable

- internal/pkg/node/constructors.go
- internal/pkg/node/datastructure.go
Prior the primary was a boolean attribute of NetDev, so several
NetDevs could have been primay. Setting is as a sting in NodeConf
assures that only one network could be primary.
If no primary network is set, a valid altvalue will be set.
> set the primary network in NodeInfo not in NetDev

- userdocs/contents/installation.rst
The CIQ repository mentioned in userdocs is expected to be decommissioned soon. Meanwhile, we have RPMs on the GitHub releases page. This updates the documentation to point to the project packages.
> Remove reference to deprecated CIQ repository

- internal/app/api/wwapird_curls/curls.sh
- internal/app/wwctl/container/imprt/root.go
- userdocs/contents/containers.rst
- userdocs/contributing/development-environment-kvm.rst
- userdocs/contributing/development-environment-vbox.rst
- userdocs/quickstart/el7.rst
- userdocs/quickstart/el8.rst
Warewulf sample node images are now built automatically with GitHub CI/CD, targeting ghcr.io. This updates the documentation to reference that location rather than DockerHub.
> Update documentation to reference ghcr rather than DockerHub

- CHANGELOG.md
- internal/pkg/api/container/container.go
add support for resolving absolute path automatically
- Fixes #493 
Before
```
[vagrant@localhost ~]$ ls
go  rocky8.tar  warewulf
[vagrant@localhost ~]$ sudo wwctl container import rocky8.tar rocky8
ERROR …
```
> add support for resolving absolute path automatically

- internal/pkg/batch/batch_test.go
This test is unreliable due to its dependency on timing. Disabling for now until a better method is implemented.
> Disable TestBatchPool

- userdocs/quickstart/el8.rst
Following the instructions [here](https://warewulf.org/docs/development/quickstart/el8.html) will fail when running `make all` on a fresh Rocky Linux 8.7 install because `gpgme-devel` and `libassum-devel` aren't installed by default.
> Add missing packages to build on EL8

- internal/app/wwctl/container/list/main_test.go
container list test can fail in wrong time zone
- Fixes #773 
> container list test can fail in wrong time zone

- CHANGELOG.md
- internal/pkg/node/constructors.go
- overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww
`netdev.OnBoot` wasn't actually configuring ifcfg ONBOOT, which was set statically to true.
- Fixes #644
> Configure ONBOOT with netdev.OnBoot

- CHANGELOG.md
- internal/pkg/node/methods.go
Node list returns node entries in random order during test, so in this PR I added sortByName support, which will always return node entries by alphbet ascending names. 
- Fixes #
> add sort support for returned entry slice

- CHANGELOG.md
- internal/app/wwctl/node/edit/main.go
fix wwctl node edit inconsistent state with warewulfd
- Fixes #691
prerequisites:
```
[vagrant@localhost warewulf]$ sudo wwctl node list -a n1 | grep hwaddr
n1    default:hwaddr   -- …
```
> fix wwctl node edit inconsistent state with warewulfd

- CHANGELOG.md
- internal/app/wwctl/overlay/imprt/main.go
- internal/app/wwctl/overlay/imprt/main_test.go
- internal/app/wwctl/overlay/imprt/root.go
wwctl overlay import: transparently create parent directories
- Fixes #608 
> wwctl overlay import: transparently create parent directories

- CHANGELOG.md
- internal/app/wwctl/node/list/main.go
- internal/pkg/api/node/list.go
originally we are using `=` as the splitter but this will prevent from printing `=` in the value.
in this PR, we are using a more completed splitter. 
- Fixes #828 
> replacing using different string spliter

- CHANGELOG.md
- userdocs/quickstart/el8.rst
* without `genconfig`, warewulfd doesn not read `/etc/warewulf/warewuld.conf`, and read `/usr/local/etc/warewulf/warewulf.conf` instead, that is inconsistent with later section on quickstart guide.
* added `genconfig` line to make our build configuration identical to rpm package for EL8, this makes build result consistent with later section on quickstart guide.
- Fixes #847
- Based this PR against the appropriate branch (typically …
> Fix build configuration on Quickstart guide

- Makefile
Building the userdocs via the command `make latexpdf` failed as `wwctl`
couldn't be build as it depends on `config` and `vendor`. This PR fixes 
this.
> fixed targets for doc build

- CHANGELOG.md
- Makefile
The wwinit overlay populates /warewulf/config with information about the
Warewulf configuration. This includes the IPMI password, which should not be
visible to regular users. This changes the installed permissions of the file to
be readable by root only.
Closes #728
> Restrict access to /warewulf/config from overlays

- CHANGELOG.md
- Makefile
- internal/app/wwctl/overlay/imprt/main_test.go
- internal/pkg/overlay/config.go
- internal/pkg/overlay/overlay.go
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/util.go
This addresses the system/runtime overlay image naming by adding an optional
argument to OverlayImage() to specify the context in which an image name is
being constructed. If set to "legacy" then the old name joining method is used.
Any other value passed is used to construct a short image name. For example,
the node config:
```
nodeprofiles:
default:
comment: This profile is automatically included for each node
container name: rocky-9
runtime overlay:
- generic
- debug
system overlay:
- wwinit
kernel:
override: rocky-9
args: selinux=0 rootfs=tmpfs consoleblank=600
nodes:
cpu-a-1:
profiles:
- default
network devices:
clusternet:
device: eth0
hwaddr: 28:80:23:e8:7b:f0
ipaddr: 100.68.0.66
primary: "true"
```
Produces the overlay images:
```
[root@micropterus overlays]# tree
.
├── cpu-a-1 …
```
> Improved overlay image naming

- CHANGELOG.md
- Makefile
- internal/app/wwctl/overlay/imprt/main_test.go
- More aggressive cleaning based on contents of .gitignore.
- Replace deprecated io.ioutil functions with new os versions.
Fix assorted build errors I encountered building on Rocky 9.2. Not sure teh OS
matters, but that is it.
> griznog fix build errors

- CHANGELOG.md
- internal/pkg/api/container/container.go
- internal/pkg/container/syncuids.go
- internal/pkg/container/syncuids_test.go
Refactors syncuids.go (syncuser) for clarity and fixes the updating of gid for container files during syncuser.
Fixes #840
> Refactor syncuids and fix GID chown

- warewulf.spec.in
The inclusion of `%{_sysconfdir}/warewulf/*` and
`%{_sysconfdir}/warewulf/nodes.conf` caused nodes.conf to be listed twice, generating a warning.
The inclusion of `%{srvdir}/warewulf`, which is redundant with `%{_sharedstatedir}/warewulf`, caused all files in
`%{_sharedstatedir}/warewulf/overlays` to be listed twice, generating a warning.
> Fix duplicate entries in rpm %files

- warewulf.spec.in
The previous PR #888 erroneously removed the %config(noreplace) macro from the nodes.conf file. This PR restores it.
> Restore %config(noreplace) to nodes.conf

- CHANGELOG.md
- internal/app/wwclient/root.go
#781 introduced a new API for reading warewulf.conf. This new API wasn't
implemented in wwclient. This PR introduces this new API to wwclient.
> fix warewulf.conf location for wwclient

- CHANGELOG.md
- CONTRIBUTORS.md
- internal/pkg/config/root.go
`wwctl` panics rather than returning an error if it cannot detect the IP address and one is not provided in config (e.g. during the build process).
Before:
```
goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/config.(*RootConf).SetDynamicDefaults(0x555b2e273340)
/var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/internal/pkg/config/root.go:123 +0xaf
github.com/hpcng/warewulf/internal/app/wwctl.rootPersistentPreRunE(0xc0002a9900?, {0xc000526be0?, 0x4?, 0x555b2d8c071b?})
/var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/internal/app/wwctl/root.go:92 +0x125
github.com/spf13/cobra.(*Command).execute(0x555b2e210720, {0xc000526bc0, 0x2, 0x2}) …
```
> add error handling to dynamic network configuration

- go.mod
- go.sum
- internal/pkg/overlay/config.go
- internal/pkg/overlay/config_test.go
- internal/pkg/overlay/overlay.go
- internal/pkg/overlay/overlay_test.go
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/provision_test.go
- internal/pkg/warewulfd/util.go
- internal/pkg/warewulfd/util_test.go
The recent PR #883 replaced the standard overlay naming convention with static names for each of the runtime and wwinit/system contexts; but the method by which it left the "legacy" naming convention in place led to a bug where warewulfd was still attempting to serve overlays with the previous naming convention, though this name wasn't being built.
This PR refactors contextual overlay image naming to be, I think, a more typical golang pattern, and updates affected code to match.
This PR also included tests for all functions modified by this change.
Fixes #896
> Fix warewulfd for new contextual overlay names

- Dockerfile
- Makefile
- Tools.mk
- Variables.mk
- userdocs/contributing/development-environment-vagrant.rst
- userdocs/quickstart/el8.rst
- userdocs/quickstart/el9.rst
- userdocs/quickstart/suse15.rst
- warewulf.spec.in
The previous PR #890 introduced a `Defaults.mk` target for defining default variables for future calls to `make`. This functionality was already present in a different form, but this new "real" target had an unintended side-effect of causing the target to be called automatically at reference, even the optional reference `-include Defaults.mk`. This is undesirable as it causes the generation of defaults even during a `make clean`.
This commit resolves these issues and further refactors the Makefile, building on the work in #890, but with additional understanding:
* Convert the `Defaults.mk` target to the "phony" `defaults` target, preventing automatic generation
* Remove `make clean` from `warewulf.spec`, expecting the contents of the dist to be appropriate
* Refactor and split `clean` …
> Updated Makefile to account for vendor/ in dist

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
- internal/app/wwctl/container/exec/child/root.go
Previously ephemeral container mounts were performed in /tmp. Now these
mounts are overlayed on the same fs as is used for chroots as fs overlays
need to be on the same fs.
Signed-off-by: Christian Goll <cgoll@suse.de>
> Epehermal container mounts on same fs as chroot

- internal/pkg/node/constructors.go
- internal/pkg/node/constuctors_test.go
- internal/pkg/node/datastructure.go
Primary network devices are now identified by a per-node attribute,
rather than a per-netdev boolean. While the legacy data can still be
parsed, the argument for setting the per-netdev boolean at the
command-line is no longer available.
Correct behavior is tested.
> Disable per-netdev primary flag

- CHANGELOG.md
- internal/app/wwctl/overlay/show/root.go
- internal/pkg/node/util.go
- internal/pkg/overlay/overlay.go
Various wwctl overlay commands just completed the overlay names. With
this PR e.g.
`wwctl overlay edit <TAB>`
will complete the available overlay names and
`wwctl overlay edit wwinit <TAB>`
will complete all the availble files in the overlay wwinit
> advanced command line completion for wwctl overlay

- CONTRIBUTING.md
- DCO.txt
Requires commit sign-off and documents the meaning of signing off for the project.
> Add CONTRIBUTING documentation with a DCO

- Makefile
All the proto stuff will be downloaded so just disable all protobuff rules and targets on OFFLINE_BUILD.
> do not download protobuf stuff on offline builds

- Makefile
- go.mod
The vendor target can't reliably determine when it needs to run, so mark it phony. At the same time, update go.mod.
> Mark vendor target phony and update

- internal/pkg/overlay/overlay.go
- internal/pkg/overlay/overlay_test.go
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/util.go
- internal/pkg/warewulfd/util_test.go
The warewulfd process called `wwctl build -O [system|runtime] node`
if autobuild was set. This created [system|runtime].img which isn't
supported with the build model. Calling now BuildOverlay directly
> calling the overlay build functions direclty

- userdocs/quickstart/el7.rst
- userdocs/quickstart/el8.rst
- userdocs/quickstart/el9.rst
- userdocs/quickstart/suse15.rst
Update some of the Quickstart documentation. 
- Update the `warewulf.conf` file to match version in `development` branch.
- Consistent flags for the `node add` syntax. 
- Change container name to `rocky-9` in the profile section of the el9 quickstart.
> Quickstart doc updates

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/workflows/check.yml
- .github/workflows/documentation.yml
- internal/app/wwctl/overlay/edit/main.go
- userdocs/conf.py
The development branch has been replaced with the main branch in GitHub. Replaces references to development in docs, commands, configuration, and workflows.
> Replace development with main

- Makefile
The linter is sometimes timing out when run by GitHub Actions. This PR changes the timeout to 5 minutes.
- Fixes #968
> Increase linter timeout to 5 minutes

- CHANGELOG.md
- internal/app/wwctl/overlay/list/main.go
- internal/app/wwctl/overlay/list/main_test.go
- internal/app/wwctl/overlay/show/main.go
- internal/app/wwctl/overlay/show/main_test.go
- internal/pkg/node/transformer_test.go
- internal/pkg/node/transformers.go
- internal/pkg/testenv/testenv.go
test for issue #967, but seems to work correctly.
Still an addtional test for the overlay tempalting has to be added.
> added test for tag from profile

- .github/actions/generate/action.yml
- .github/actions/rpm/action.yml
- .github/workflows/nightly.yml
- CHANGELOG.md
There is an issue that the option `update_latest_release` in the nightly release will try updating existing published release first. This should be avoided.
- Fixes #969
> [hotfix for nightly release]remove update_latest_release

- .github/actions/generate/action.yml
- .github/actions/rpm/action.yml
- .github/workflows/nightly.yml
Add git tag into nightly releases items.
- Fixes #
> add git tag to nightly release

- internal/pkg/node/constructors.go
setting the ConfigFile (location of nodes.conf) in init()
led to the situation that a configured Paths.Sysconfdir is ignored.
> moved initialization of ConfigFile to New()

- internal/pkg/container/syncuids.go
As warewulf should be warm and welcoming, don't show a scary error if there is
uid/gid mismatch. Logically this is an error but scares the hell out of
inexperienced users.
> warn and don't show scary error on syncuids

- userdocs/index.rst
- userdocs/quickstart/debian12.rst
- Added file `userdocs/quickstart/debian12.rst`  
- Added the corresponding entry in the Quickstart toctree in  `userdocs/index.rst`
Since a Debian 12 container image has recently been added to the project (https://github.com/hpcng/warewulf-node-images/pull/33) a Debian 12 Quickstart guide may be desirable. It can be the smooth initial path for those who are most familiar to Debian, Ubuntu and derivatives.
-  #867
I have
> Add Debian quickstart

- internal/pkg/config/tftp.go
IPXESOURCE is pointing to /usr/share/ipxe/ by default, so the `ipxe/` directory should not be included in the compiled-in relative defaults.
Fixes a bug in #1010
> Fix relative iPXE paths

- Variables.mk
The godeps macro is used by the Makefile to determine if golang binaries need to be rebuilt based on changes to their dependencies, which may include libraries in vendor. This produces errors if the vendor directory is not present.
This change suppresses error messages during dependency resolution.
> Suppress vendor errors in makefile

- CHANGELOG.md
- internal/pkg/wwlog/wwlog.go
Better way in my opinion to close #1000 as fmt.Printf shouldn't 
be used in normal code base
> separate writer for wwlog.Info

- containers/README.md
warewulf-node-images has moved to
github.com/warewulf/warewulf-node-images
> Update path to warewulf-node-images

- CHANGELOG.md
- internal/app/wwctl/node/set/main_test.go
- internal/pkg/node/transformers.go
This PR helps fix the issue that profile existing tag won't be added to the node configuration. The patch fixes the issue by updating the map value if key already exists.   
- Fixes #967
- Fixed #1056
> Fix the issue that the same tag added via `node set` is ignored

- CHANGELOG.md
- internal/pkg/overlay/config.go
change message level of too-verbose messages from warn to debug. 
- Fixes #1025
> change message level from warn to debug

- CHANGELOG.md
- overlays/wwinit/warewulf/init.d/50-ipmi
- overlays/wwinit/warewulf/init.d/90-selinux
renaming and uniforming the shebang of scripts in folder init.d to `#/bin/sh`. 
- Fixes #821
> refactor the shebang usage in scripts of init.d folder

- CHANGELOG.md
- CONTRIBUTORS.md
- overlays/wwinit/etc/NetworkManager/system-connections/ww4-managed.ww
- userdocs/contents/nodeconfig.rst
The changes to `ww4-managed.ww` enable users to create bonded network interfaces.
> Enable creating a bonding network interface

- CHANGELOG.md
- overlays/wwinit/warewulf/init.d/80-wwclient
80-wwclient was previously supplanted by 80-wwclient.ww, but the static version was retained. Meanwhile, the static version can only detect systemd when it is running, which it isn't during wwinit. This led to wwclient starting during wwinit and then being killed by systemd.
- Closes #1066
> Remove redundant wwclient startup script

- CHANGELOG.md
- Variables.mk
- cmd/update_configuration/vers43/nodes.conf
- docs/man/man5/warewulf.conf.5
- internal/app/wwctl/root.go
- internal/pkg/config/buildconfig.go.in
- internal/pkg/config/root_test.go
- internal/pkg/overlay/funcmap_test.go
- internal/pkg/testenv/testenv.go
- internal/pkg/version/version.go
- userdocs/contents/configuration.rst
- userdocs/contributing/development-environment-vagrant.rst
- userdocs/quickstart/debian12.rst
- userdocs/quickstart/el8.rst
- userdocs/quickstart/el9.rst
Updated the metadata for the 4.5.0rc1 release. Its a quite big
patch as
* for the config files the confversion 45 must be set seperately
* tests get the version by the compiled in confversion
Also Version and Release are now const strings to make obivous
that this values can't be changed, as this might be suggested by
unexported variables.
@anderbubble must be rebased after #1037 is merged
> Update metadata for 4.5.0rc1 release

- .github/workflows/documentation.yml
Docs CI workflow was not installing graphviz, leading to unrendered diagrams.
- Fixes #1105
> Install Graphviz in userdocs CI workflow

- warewulf.spec.in
CentOS 7 only has ipxe-bootimgs, so update requires in the RPM when building for el7.
> Fix ipxe-bootimgs in warewulf.spec.in for el7

- CHANGELOG.md
- CONTRIBUTORS.md
- internal/app/wwclient/root.go
Allow machines without a SMBIOS to run wwclieint.  The Raspberry Pi is one such machine.  The PR will try to read from "/sys/firmware/devicetree/base/serial-number" if there is no SMBIOS (Raspberry Pi Serial Number) and create a UUID from that.
- Fixes warewulf/warewulf#1108
> Add support for machines that do not have a SMBIOS

- CHANGELOG.md
- internal/app/wwctl/profile/list/main.go
- internal/pkg/api/profile/list.go
Fixed a bug with profile list when kernelargs are set with 'var=val' format. This also removed the unnecessary '--' for the source profile since it's never used.
If kernelargs are set, `profile list -a` format is messed up due to profile uses '=' as separator, e.g.,
```
PROFILE  FIELD                        PROFILE  VALUE
default  Id                           --       default
default  Comment                      --       This profile is automatically included for each node
default  Kernel.Args                  --       crashkernel                                           no vga  791 net.naming-scheme  v238
```
This fix standardized the field separator to ':=:' which is what node uses.
> Fixed profile list bug

- CHANGELOG.md
- userdocs/contents/boot-management.rst
A minor typo in the rst formatting was causing the code block demonstrating how to configure `grubboot: true` to not render.
> Fix a formatting error hiding GRUB configuration

- CHANGELOG.md
- overlays/wwinit/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
- overlays/wwinit/rootfs/etc/resolv.conf.ww
- overlays/wwinit/rootfs/etc/sysconfig/network-scripts/ifcfg.ww
- overlays/wwinit/rootfs/etc/systemd/system/ww4-disks.target.ww
- overlays/wwinit/rootfs/etc/systemd/system/ww4-mounts.ww
sprig replaces `slice` with a function that only operates on sprig lists. `substr` is required for use with strings.
- Fixes: #1139
Fixes a regression that occurred at #1030.
> Replace slice in templates with sprig substr

- .github/workflows/check.yml
- CHANGELOG.md
- go.mod
This PR requires minimum go version 1.20
https://github.com/warewulf/warewulf/pull/1122
- Fixes #
> upgrade golang version to 1.20

- CHANGELOG.md
- internal/app/wwctl/overlay/show/main.go
- internal/app/wwctl/overlay/show/main_test.go
Add support to render template using `host` or `$(uname -n)` as the value of command `overlay show --render`
- Fixes #623
> add support to render template using `host` or `$(uname -n)` as the value of command `overlay show --render`

- CHANGELOG.md
- userdocs/contents/configuration.rst
> Document overriding paths in warewulf.conf

- CHANGELOG.md
- Makefile
Building protocol buffers requires fetching utilities from the Internet. Typically this is done at development time and the finished buffers are included in dist; but if timestamps get off this can lead mock to try to rebuild them during an offline build, causing the build to fail.
This change moves all of the protoc targets into a section of the Makefile that is disabled during an offline build.
- Closes #1155
> Never attempt to build protocol buffers offline

- userdocs/contents/containers.rst
Changed typo in the word "belonging"
- Fixes #
> changed typo in the word belonging

- CHANGELOG.md
- internal/pkg/warewulfd/status.go
the nmode status database, although not critical to 
warewulfd, didn't have a lock against concruent access.
close #1174
> add a read write mutex for node status

- CHANGELOG.md
- internal/app/wwctl/overlay/show/main_test.go
- internal/pkg/overlay/datastructure.go
- internal/pkg/overlay/overlay.go
- overlays/debug/rootfs/warewulf/template-variables.md.ww
{{ .Overlay }} contains the overlay name in which the template is located, otherwise
its values is "UNDEF" if the RenderTempalte is called outside the warewulf
overlay tree
* Closes #1052
> added {{ .Overlay }} to templates

- CHANGELOG.md
- Makefile
- warewulf.spec.in
A recent security update breaks compatibility with CentOS 7 through gpgme. This change omits building the API by default and does not build it when packaging for EL 7.
- Closes #1171
> Don't build the API for CentOS 7

- .github/workflows/tagged-release.yml
Dynamic versioning of Warewulf releases broke the release process. This simplifies and fixes finding of release artifacts during tagged-release.
This also removes CentOS 7 as a release target, as previous attempts to fix building on CentOS 7 by omitting the API still failed to run the testsuite.
> Update tagged-release to accommodate new artifact names

- .github/workflows/tagged-release.yml
Tags are required for dynamic version generation.
> Fetch tags during tagged-release

- .github/workflows/tagged-release.yml
Tags are required during tagged-release, but attempting to fetch only tags caused an error of the form:
```
Cannot fetch both <sha> and refs/tags/<name> to refs/tags/<name>
```
Switching to just downloading all history.
> Fetch all history during tagged-release

- scripts/get-version.sh
GitHub tags for draft releases are lightweight tags.
> Use lightweight tags when generating version

- CHANGELOG.md
- internal/app/wwctl/node/list/main_test.go
- internal/pkg/node/datastructure.go
- internal/pkg/node/methods.go
This is freaking change, as normaly I wouldn't touch Entry,
but as Entry will go away in the future, get this done with
this ugly workarround.
- add various tests for `wwctl node list -a`
- Entry is aware if its ment as a slice or not
> Correct output for wwctl node list -a for slices

- CHANGELOG.md
- internal/pkg/container/syncuids.go
syncuser walks the container file system to see what files need to be updated; but in the past this has been done regardless of whether syncuser is actually running in write mode. Since walking the file system isn't necessary to determine if syncuser is warranted, only walk when writing.
This prevents an unnecessary and otherwise unavoidable file system walk when importing a new container, which, for large containers, can add significant wait time.
> Only walk the filesystem during syncuser if writing

- CHANGELOG.md
- internal/pkg/container/syncuids.go
A previous fix for #527 broke parsing of /etc/group. This PR allows parsing of both /etc/passwd and /etc/group.
- Fixes #1202
> Fix parsing of /etc/group during syncuser

- .github/actions/generate/action.yml
- .github/actions/rpm/action.yml
- .github/workflows/nightly-release.yml
- CHANGELOG.md
`$(rpm -q --qf "%{RELEASE}\n" --specfile warewulf.spec` now returns a slightly changed release info, causing the failure of nightly build failure. Also we need to remove the old centos 7 build. 
- Fixes #1195
Build on my repo
> fix the nightly release build failure

- CHANGELOG.md
- CONTRIBUTORS.md
- overlays/host/rootfs/etc/dnsmasq.d/ww4-hosts.conf.ww
Dnsmasq seems to use the most recently applied configuration to a client. If you opt to use dnsmasq as is, what happens is the client just boots infinitely continually grabbing the ipxe image instead of the second stage.
Fixes #1146
> Reorder dnsmasq config template to put iPXE last

- CHANGELOG.md
- userdocs/contents/containers.rst
`wwctl container import` can use `HTTP_PROXY` et al to configure an HTTP proxy. This PR adds some documentation about this support.
> Document HTTP proxy environment variables

- CHANGELOG.md
- internal/pkg/warewulfd/provision.go
Requests to provision arbitrary overlays in `secure` mode should come from a privileged source port.
The provisioning stage query parameter is currently meaningless when a specific overlay is requested, and cannot be relied upon to indicate the type of overlay being requested.
- Fixes #
> Prevent insecurely provisioning arbitrary overlays in secure mode

- CHANGELOG.md
- userdocs/contents/installation.rst
- **Point URL to warewulf github instead of hpcng.**
- **Update CHANGELOG.md for this PR.**
> Point to warewulf github in installation docs

- CHANGELOG.md
- internal/pkg/config/root.go
when parsing warewulf.conf, CIDR format will cause issue.
- Fixes #1130
> add CIDR format to warewulf.conf parse

- CHANGELOG.md
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/syncuser/main.go
- internal/pkg/api/container/container.go
- internal/pkg/container/syncuids.go
This PR refactors syncuser to only walk the container fs twice: once for user changes and once for group changes. The previous implementation of syncuser walked the container file system for every user and group being sync'd. This caused syncuser to take a very long time when large images were combined with large user/group counts.
This PR also changes the (internal) semantics of syncuser to consistently use a "write" boolean throughout, rather than "write" in some places and "showOnly" in others.
To reduce some frequently-observed confusion, `wwctl container import` has been adjusted to only run syncuser if `--syncuser` is specified, rather than always running it in "showOnly" mode when `--syncuser=false`. This eliminates a spurious "error" report for users who do not intend to use …
> Refactor syncuser to reduce walks of the container fs

- CHANGELOG.md
- Makefile
- Variables.mk
- dracut/modules.d/90wwinit/load-wwinit.sh
- dracut/modules.d/90wwinit/module-setup.sh
- dracut/modules.d/90wwinit/parse-wwinit.sh
- etc/grub/grub.cfg.ww
- etc/ipxe/dracut.ipxe
- internal/pkg/container/config.go
- internal/pkg/container/config_test.go
- internal/pkg/warewulfd/parser.go
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/provision_test.go
- overlays/wwinit/rootfs/etc/NetworkManager/conf.d/ww4-discard-configuration.conf
- overlays/wwinit/rootfs/warewulf/init.d/90-selinux
- userdocs/contents/boot-management.rst
- warewulf.spec.in
Support booting a dracut image from a container and using it to bootstrap a large container.
- Closes #1115
> Dracut initramfs boot

- .github/actions/prepare/action.yml
- CHANGELOG.md
Some PRs require the `go mod tidy` after `go mod vendor`
See: https://github.com/warewulf/warewulf/actions/runs/9412139832/job/25926760773?pr=1217
- Fixes #
> run go mod tidy after go mod vendor

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
- internal/app/wwctl/container/exec/child/root.go
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/exec/root.go
- internal/pkg/config/root.go
- internal/pkg/config/root_test.go
- internal/pkg/container/config.go
- Close #1180
- Close #830
- using the right overlay directory and remove it
- use warewulf.conf from parent on child
The directories for the overlays needed for the bind mount are now created under `conf.Paths.WWChrootdir/$CONTAINERNAME/run`. This directory can be used as lock, so that there can't be congruent shell/exec calls to the same container.
> Fix overlay directory location/creation

- CHANGELOG.md
- CONTRIBUTORS.md
- internal/pkg/util/util.go
- internal/pkg/util/util_test.go
The `/etc/warewulf/excludes` file is currently broken in two ways: It doesn't work correctly with either leading or trailing slashes. This is due to the underlying `FindFilterFiles` function relying on string comparisons via `filepath.Match`, which don't allow trailing slashes in the patterns, and the fact that we are using relative paths, which makes the leading slash incorrect as well. This PR fixes the issues and adds a test to prevent regressions in the future.
> Fix excludes

- CHANGELOG.md
- internal/pkg/overlay/overlay.go
- internal/pkg/overlay/overlay_test.go
The root cause of this mentioned issue is that 
https://github.com/warewulf/warewulf/blob/a0bec6bf60125bcdd52350fd99935f07259c8441/internal/pkg/overlay/overlay.go#L130
`overlayNames` var is empty when calling with url mentioned in the following issue ticket.
So in this PR, we've added building system/runtime overlay specified by context
- Fixes #1216
- Fixed #1240 
Does not send overlay request parameters won't cause this issue any longer. 
```
[root@localhost warewulf]# curl -v --local-port 500-1000 'http://localhost:9873/provision/11:22:33:44:55:66?stage=runtime'
*   Trying 127.0.0.1:9873...
* Local port: 500
* Connected to localhost (127.0.0.1) port 9873 (#0)
> GET /provision/11:22:33:44:55:66?stage=runtime HTTP/1.1
> Host: localhost:9873
> User-Agent: curl/7.76.1
> Accept: */*
> 
* …
```
> fix the issue that system/runtime overlays are not auto-rebuilt

- CHANGELOG.md
- internal/app/wwclient/root.go
- overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
- overlays/host/rootfs/etc/dnsmasq.d/ww4-hosts.conf.ww
The default dhcpd.conf.ww in the host overlay does not pass the asset-tag to the next-server filename, this adds the asset-tag and uuid to the filename parameter to allow nodes to boot with asset-tags configured. 
This also update enables wwclient to utilize dmidecode for retrieving the node asset tag when the SMBIOS does not provide a valid asset tag. This enhancement requires that dmidecode be installed within the container. If dmidecode is not installed, wwclient will continue to operate, but the asset tag may default to "Unknown". An alternative approach could involve reading from the kernel file system at /sys/devices/virtual/dmi/id/chassis-asset-tag. However, the consistency of this path across different kernel versions is uncertain.
- Fixes #1110
> Asset-tag fixes in dhcpd.conf.ww and wwclient 

- CHANGELOG.md
- internal/pkg/util/util.go
- internal/pkg/util/util_test.go
The use of `os.Stat` caused `FindFilterFiles` to look at symlink targets rather than symlinks themselves. This made it impossible to include a dangling symlink in a container image.
This PR uses `os.Lstat` to inspect symlinks directly.
- Fixes #1267
> Capture "broken" symlinks during container build

- CHANGELOG.md
- overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
- Disable dynamic pool when using static dhcp
- Populate configuration of non-primary interfaces for static dhcp
This behavior appears to have been changed somewhat accidentally during the implementation of GRUB booting.
> Restore previous behavior of static dhcp

- CHANGELOG.md
- internal/app/wwctl/overlay/edit/main.go
It looks like this PR can fix two issues at the same time. (issue #1235 and issue #1236)
By directly doing `os.Rename` from temp file created each time for the edit to the targeted overlay file, we can solve the both issues at the same time. 
- Fixes #1235 
- Fixes #1236 
https://github.com/warewulf/warewulf/assets/2051711/bbad7ebc-1a6e-40bb-a167-2b64b1c3ceb5
> fix the issue that new files created via wwctl overlay edit have permission 755 && removing lines during wwctl overlay edit didn't work

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
Also unify mounting of sys, run, proc, and dev as occuring within the chroot and without bind mounts from the host.
mount /sys and /run during container exec.
Also unify mounting of sys, run, proc, and dev as occuring within the chroot and without bind mounts from the host.
- Replaces #1287
> mount /sys and /run during container exec

- CHANGELOG.md
- internal/pkg/container/syncuids.go
- internal/pkg/container/syncuids_test.go
The lines +::::: or +::: are used in passwd/group as
placeholer for users added form the network via ldap/nis/sssd.
These lines should not trigger a warning.
> ignore +:: style lines in passwd/group

- CHANGELOG.md
- internal/pkg/kernel/kernel.go
- internal/pkg/kernel/kernel_test.go
Accept `+` within kernel release version strings.
`kernel-64k` from the Rocky9 repos has a kernel release of `5.14.0-427.18.1.el9_4.aarch64+64k` which doesn't match the pattern Warewulf currently checks.
```bash
DEBUG  : Set log level to: 10, DEBUG
DEBUG  : Reading warewulf.conf from: /etc/warewulf/warewulf.conf
DEBUG  : Checking if path exists as a directory: /var/lib/warewulf/chroots/test_arm/rootfs
DEBUG  : root: /var/lib/warewulf/chroots/test_arm/rootfs
DEBUG  : Looking for kernel version with pattern at: /var/lib/warewulf/chroots/test_arm/rootfs/boot/Image-*
DEBUG  : Looking for kernel version with pattern at: /var/lib/warewulf/chroots/test_arm/rootfs/boot/vmlinuz-linux
DEBUG  : Looking for kernel version with pattern at: /var/lib/warewulf/chroots/test_arm/rootfs/boot/vmlinuz-*
DEBUG …
```
> Accept + within kernel versions

- Makefile
`make dist` may accidentially include previously-made dist tarballs; this change adjusts the target to exclude these tarballs from the dist.
> Prevent make dist from including previous dists

- CHANGELOG.md
- internal/pkg/warewulfd/util.go
Following #1249, autobuilt overlays were being built with no contents.
This change follows the pattern in `wwctl overlay build` to include configured overlays when none are explicitly specified.
Inspired by #1296.
> Ensure autobuilt overlays include contextual overlay contents.

- userdocs/contents/boot-management.rst
Moves dracut docs to their own heading. Previously they were drafted under iPXE because it only worked with iPXE; but support for Grub was added without fixing the docs.
> Move dracut docs to their own heading

- CHANGELOG.md
- internal/app/wwclient/root.go
- internal/pkg/config/root.go
- internal/pkg/config/wwclient.go
With this change, you can specify a port number for wwclient. If
```
wwclient:
port: NUMBER
```
is specified in warewulf.conf, wwclient will bind to the specified local port NUMBER. If no port is specified, wwclient will use any available port, or port 987 if secure is true.
Port 987 is in the default port range used by the Linux NFS client (665-1023, see linux/include/linux/sunrpc/xprtsock.h). Changing the port can avoid failures when port 987 is already in use.
We want wwclient to use a port <1024. Currently, the way to achieve this is to set "secure" to true in warewulf.conf.
But sometimes, wwclient fails to start, because port 987 is already in use by the Linux kernel NFS client.
We see two options to avoid this conflict.
a) Set min_resvport or max_resvport kernel parameters for the …
> Add option for wwclient port number

- CHANGELOG.md
- internal/app/wwclient/root.go
- **Sanitize/escape asset tag strings from dmidecode.**
- **Update CHANGELOG.md**
When `wwclient` falls back to `dmidecode` it's possible to get values which
have spaces and posisbly other characters not friendly to URLs. This PR uses
the `net/url` package to properly escape the `dmidecode` result for the asset
tag.
- Closes #1310
> sanitize wwclient url data

- internal/pkg/node/constructors.go
> removed dead `boot method` from defaults.conf

- CHANGELOG.md
- userdocs/contributing/documentation.rst
- **Replace warewulf-web with warewulf in contributing links.**
- **Update CHANGELOG for PR.**
> Fix old links that pointed to warewulf-web

- internal/pkg/api/profile/profile.go
"allready" should be "already"
> Fix typo in "profile with name ... already exists" message

- CHANGELOG.md
- userdocs/contents/boot-management.rst
The current command line works correctly only if one kernel is installed. It picks the oldest if there are multiple, which is rather unlikely to be correct. Using "tail" instead of "head" would work also, but `--regenerate-all` makes it briefer and safer.
> docs: fix dracut build command in docs

- CHANGELOG.md
- internal/app/wwclient/root.go
Generalizes @griznog's fix in #1309 to all arguments, utilizing `url.URL` to build the url used by `wwclient`.
> Refactor url build in wwclient with url.URL

- userdocs/contents/containers.rst
I added a subsection to user docs about using QEMU to work with containers of various architectures
- Addresses #1323
> Update containers.rst to include QEMU multiarch

- CHANGELOG.md
- internal/app/wwctl/overlay/show/main.go
`wwctl overlay show --render` shows the rendered overlay with `wwlog.Info`, but that caused it to be processed as a format string. This passes an explicit format string first, and then includes the rendered overlay as a variable to the formatter.
- Fixes #1363
> Prevent overlays from being improperly used as format strings

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/exec/root.go
- internal/app/wwctl/container/shell/root.go
- internal/pkg/config/mounts.go
- internal/pkg/container/mountpoints.go
- userdocs/contents/containers.rst
The option cow can now be set for files which are then
mounted during exec, but copied into the image and removed
if not modified.
Example:
```
wwctl container shell leap15.6 --bind /root/test:/root/test:cow
```
> add cow option for binds

- CHANGELOG.md
- CONTRIBUTORS.md
- dracut/modules.d/90wwinit/load-wwinit.sh
- dracut/modules.d/90wwinit/module-setup.sh
- dracut/modules.d/90wwinit/parse-wwinit.sh
- etc/grub/grub.cfg.ww
- etc/ipxe/dracut.ipxe
- warewulf.spec.in
Alternative implementation for #1269. Also incorporates a fix from #1370.
The new dracut boot method bloated /proc/cmdline, and exposed asset-tag and uuid to unprivileged users. This PR moves the parsing of dracut URIs from iPXE to the dracut script pase-wwinit.sh, using dmidecode to obtain asset-tag and uuid, leaving only the IP and port of the warewulf server in /proc/cmdline.
Additionally, it forces runtime overlays to be pulled from a static local port (986) to allow dracut boot to be used with secure mode. Port 986 is used instead of 987 to prevent a race condition of the system releasing the port before wwclient starts and tries to bind to 987.
Lastly, add the required curl, cpio and now dmidecode packages to warewulf.spec for warewulf-dracut subpackage
- Fixes #1261
> Dracut boot refinement

- CHANGELOG.md
- internal/pkg/oci/puller.go
- internal/pkg/oci/puller_test.go
Return an error indicating that name should not contain colon when importing containers
- Fixes #1371
> Return an error indicating that name should not contain colon when importing containers

- CHANGELOG.md
- internal/app/wwctl/overlay/build/main.go
If `wwctl overlay build` fails, currently we only print a warning. This should be an error instead, to be used in scripts
- Partial fix for #1390
> Return error code if overlay build fails

- CHANGELOG.md
- CONTRIBUTORS.md
- etc/grub/chainload.ww
- etc/grub/grub.cfg.ww
This fixes asset key retrieval in the rendered grub.cfg and adds it to the chainload grub.cfg, allowing asset key based grub boot to work. 
- `--type1` should be `--type 1`
- The `chassis-asset-tag` (as used elsewhere), is not in the type 1 tabke, but in the type 3 table. 
- If an asset tag is listed in the node config, it is checked by wwctl server on all requests, so everything using `(http,<ip:port)` must also use `?assetkey=${assetkey}`, including fetching the templated grub.cfg. 
Note that this is not a full fix. The grub.efi files supplied with Rocky 9.4 do not include the `smbios` command! This has been the case for many years, apparently. I have used a Debian box to run `grub2-makenetdir`, generating a working grub efi.
With that, it is now working.
For testing, you can add an …
> Fix grub asset key handling

- userdocs/contents/nodeconfig.rst
- userdocs/contents/overlays.rst
The default naming scheme suggested in the documentation (eth0) can cause issues due to race conditions in device enumeration. Their usage in `.link` systemd unit files is discouraged https://github.com/systemd/systemd/issues/16665 and I've observed network interfaces getting named incorrectly if their name is already in use during boot.
To avoid this issue, I want to add a note mentioning the preferred naming scheme (predictable naming based on what the OS would do anyways).
Ideally, I would prefer if we would not have to deal with interface names at all, and could just use MAC addresses to identify the interfaces, but that would probably be much harder to do correctly.
> Improve network interface documentation

- CHANGELOG.md
- dracut/modules.d/90wwinit/load-wwinit.sh
- overlays/wwinit/rootfs/init
Configures Warewulf tmpfs to interleave across all available NUMA nodes.
- Closes #1347
> Set mpol=interleave on dracut tmpfs

- CHANGELOG.md
- CONTRIBUTORS.md
- overlays/wwinit/rootfs/init
This PR refactors `/init` in the wwinit overlay to more properly address the rootfs option.
After a discussion with @anderbubble about tmpfs vs ramfs vs rootfs, and some light reading about [how the kernel deals with the initramfs](https://www.kernel.org/doc/html/latest/filesystems/ramfs-rootfs-initramfs.html#what-is-rootfs), and poking around in the provisioning environment with a Rocky 8 kernel (4.18.0-425.19.2.el8_7.x86_64), it is apparently true that if a kernel is configured with `CONFIG_TMPFS=y` then it will default to establishing the initial rootfs as a tmpfs implicitly. This makes the default value of `initramfs` for  the `root` property for nodes/profiles a non sequitur, as `initramfs` no longer appears to me to have any intrinsic meaning. This refactoring attempts to address …
> Init rootfs fixes

- CHANGELOG.md
- internal/app/wwctl/container/copy/main.go
Return non-zero exit code on container copy failure
- Fixes #1377
```
[root@localhost test]# wwctl container copy rockylinux-9 rockylinux-9-tmp
ERROR: an other container with name: rockylinux-9-tmp already exists in sources
[root@localhost test]# echo $?
255
```
> Return non-zero exit code on container copy failure

- CHANGELOG.md
- internal/pkg/container/imprt.go
`copy.DirCopy` is internal and needs Init to be called
- Closes #1244 
Re-submission of #1246
> Fix panic on container import

- CHANGELOG.md
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/shell/main.go
- internal/app/wwctl/container/shell/root.go
Added --syncuser flag to shell command to enhance the user sync function. exec command supports --syncuser command but to trigger it, it requires userdbChanged && SyncUser flag set. shell command can now pass --syncuser flag to exec command to trigger it.
- Fixes #1344
> Add --syncuser flag to wwctl shell

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/list/main.go
- internal/app/wwctl/container/rename/main.go
- internal/app/wwctl/container/shell/main.go
- internal/app/wwctl/container/syncuser/main.go
- internal/pkg/api/container/container.go
return non-zero exit code on container sub-commands
- Fixes #1414
> return non-zero exit code on container sub-commands

- CHANGELOG.md
- internal/app/wwctl/container/exec/main.go
Additional help test when container.RunDir already exists
- Closes #1389
> Additional help test when container.RunDir already exists

- overlays/wwinit/rootfs/etc/wicked/ifconfig/ifcfg.xml.ww
#1410 introduced a regression in the "wicked" template by switching from the local `.NetDevs` data to `.ThisNode.NetDevs` where `IpCIDR` isn't populated correctly. (See also #1413 for underlying issue.)
This PR returns to using `.NetDevs` for `IpCIDR` until the underlying issue is fixed (possibly by #1020).
> Fix a "wicked" ifcfg overlay regression

- CHANGELOG.md
- internal/app/wwctl/node/console/main.go
- internal/app/wwctl/node/edit/main.go
- internal/app/wwctl/node/export/main.go
- internal/app/wwctl/node/imprt/main.go
- internal/app/wwctl/node/sensors/main.go
- internal/app/wwctl/node/set/main.go
- internal/pkg/api/node/node.go
Return non-zero exit code on node sub-commands
- Fixes #1421
> Return non-zero exit code on node sub-commands

- CHANGELOG.md
- userdocs/contents/security.rst
Previous versions of Warewulf v4 required a kernel argument rootfstype=ramfs to be set, in addition to --root=tmpfs. This was fixed in #1401.
- Closes #1001
> Update SELinux documentation to address rootfstype=ramfs

- CHANGELOG.md
- internal/pkg/node/ignition.go
- overlays/ignition/internal/ignition_test.go
Now that we're testing IgnitionJson, we exposed the fact that the file systems weren't being output in a consistent way. Since they're read from a map and output as a list, the order of that list was non-deterministic.
This PR sorts the file systems by device name.
- Closes #1433
> Update IgnitionJson to sort the list of file systems

- CHANGELOG.md
- internal/app/wwctl/overlay/build/main.go
- internal/pkg/overlay/overlay.go
- internal/pkg/util/util.go
Change the permission of overlay dir to `0750` and generated overlays to `0660`
- Fixes #1388
```
[root@localhost warewulf]# wwctl overlay build --nodes -O host
Building overlay for n1: [host]
Created image for overlay n1/[host]: /var/local/warewulf/provision/overlays/n1/host.img
Compressed image for overlay n1/[host]: /var/local/warewulf/provision/overlays/n1/host.img.gz
[root@localhost warewulf]# ls -al /var/local/warewulf/provision/overlays/
total 0
drwxr-x---. 3 root root 16 Sep 27 06:21 .
drwxr-xr-x. 5 root root 53 Sep 27 06:21 ..
drwxr-x---. 2 root root 41 Sep 27 06:21 n1
[root@localhost warewulf]# ls -al /var/local/warewulf/provision/overlays/n1/
total 12
drwxr-x---. 2 root root   41 Sep 27 06:21 .
drwxr-x---. 3 root …
```
> Change the permission of overlay dir to `0750` and generated overlays to `0660`

- CHANGELOG.md
- internal/app/wwctl/power/cycle/main.go
- internal/app/wwctl/power/cycle/root.go
- internal/app/wwctl/power/off/main.go
- internal/app/wwctl/power/off/root.go
- internal/app/wwctl/power/on/main.go
- internal/app/wwctl/power/on/root.go
- internal/app/wwctl/power/reset/main.go
- internal/app/wwctl/power/reset/root.go
- internal/app/wwctl/power/soft/main.go
- internal/app/wwctl/power/soft/root.go
- internal/app/wwctl/power/status/main.go
- internal/app/wwctl/power/status/root.go
wwctl should return non-zero exit code on wwctl power sub-commands
- Fixes #1439
> wwctl should return non-zero exit code on wwctl power sub-commands

- CHANGELOG.md
- internal/app/wwctl/node/set/root.go
`wwctl node set` requires mandatory pattern input
- Fixes #502
> `wwctl node set` requires mandatory pattern input

- CHANGELOG.md
- CONTRIBUTORS.md
- userdocs/contents/configuration.rst
Added a note to `configuration.rst`, so that when `nodes.conf` or `warewulfd.conf` are edited, `systemctl restart warewulfd` has to be enacted.
- Fixes # - N/A
- [x ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
Observed the following when `git commit --signoff` was ran:
```
howard@ciq ~/g/warewulf (metalllinux)> git commit --signoff
On branch metalllinux
nothing to commit, working tree clean
```
> Updated configuration.rst, CONTRIBUTORS.md and CHANGELOG.md

- CHANGELOG.md
- internal/pkg/api/node/node.go
Fix issue that domain globs not supported during wwctl node delete.
- Fixes #1449
```
[root@localhost warewulf]# wwctl node list
NODE NAME  PROFILES  NETWORK
[root@localhost warewulf]# wwctl node add n[1-9].cluster2
Added node: n1.cluster2
Added node: n2.cluster2
Added node: n3.cluster2
Added node: n4.cluster2
Added node: n5.cluster2
Added node: n6.cluster2
Added node: n7.cluster2
Added node: n8.cluster2
Added node: n9.cluster2
[root@localhost warewulf]# wwctl node list
NODE NAME    PROFILES  NETWORK
n1.cluster2  default
n2.cluster2  default
n3.cluster2  default
n4.cluster2  default
n5.cluster2  default
n6.cluster2  default
n7.cluster2  default
n8.cluster2  default
n9.cluster2  default
[root@localhost warewulf]# wwctl node …
```
> Fix issue that domain globs not supported during wwctl node delete.

- warewulf.spec.in
By default, these get `755` permissions set by git, which is too relaxed.
- Fixes #1452 
> Set restrictive permissions on `/root/.ssh` in generic overlay

- internal/pkg/api/node/add.go
Just removes an erroneous colon suffix in a log message.
> Added node: %s:
becomes
> Added node: %s
The previous format makes it seem like some extra output is missing.
> Remove an erroneous colon suffix from a log message

- CHANGELOG.md
- warewulf.spec.in
By default, these get 755 permissions set by git, which is too relaxed.
This fixes or addresses the following GitHub issues:
Fixes #1452
> Apply #1454 to main: Set restrictive permissions on /root/.ssh in generic overlay

- CHANGELOG.md
- internal/app/wwctl/kernel/delete/main.go
- internal/app/wwctl/kernel/imprt/main.go
- internal/app/wwctl/kernel/list/main.go
wwctl should return non-zero exit code on wwctl kernel sub-commands
- Fixes #1437
> wwctl should return non-zero exit code on wwctl kernel sub-commands

- CHANGELOG.md
- internal/app/wwctl/profile/add/main.go
- internal/app/wwctl/profile/delete/main.go
- internal/app/wwctl/profile/edit/main.go
- internal/app/wwctl/profile/set/main.go
Return non-zero exit code on profile sub-commands
- Fixes #1435
> Return non-zero exit code on profile sub-commands

- CHANGELOG.md
- internal/app/wwctl/overlay/build/main.go
- internal/app/wwctl/overlay/chmod/main.go
- internal/app/wwctl/overlay/chown/main.go
- internal/app/wwctl/overlay/create/main.go
- internal/app/wwctl/overlay/delete/main.go
- internal/app/wwctl/overlay/edit/main.go
- internal/app/wwctl/overlay/imprt/main.go
- internal/app/wwctl/overlay/mkdir/main.go
- internal/app/wwctl/overlay/show/main.go
Return non-zero exit code on overlay sub-commands
- Fixes #1423
> Return non-zero exit code on overlay sub-commands

- CHANGELOG.md
- CONTRIBUTORS.md
- overlays/wwinit/rootfs/init
- overlays/wwinit/rootfs/warewulf/wwinit
- scripts/build-ipxe.sh
While building and testing WW4 under Ubuntu 22.04 LTS and 24.04 LTS, it was discovered that several scripts broke due to Ubuntu/Debian use of /bin/dash instead of /bin/bash for /bin/sh. The scripts are:
overlays/wwinit/rootfs/warewulf/wwinit
overlays/wwinit/rootfs/init
scripts/build-ipxe.sh
Since Ubuntu and Debian both use dash, POSIX compliance is warranted. A simple workaround would be to force the use of bash, however, POSIX compliance is preferred in the event that bash is not available on the system, or some other environment requires it.
I have added commented out logic in the wwinit script to facilitate testing for the .sh suffix and exec bit on the scripts launched should that become needed.
- Fixes #1464 
[wwinit.txt](https://github.com/user-attachments/files/17576207/wwinit.txt) …
> Fixes  POSIX syntax for several scripts #1464 

- warewulf.spec.in
Fixes a bug introduced in #1456
> Fix warewulf.spec.in to use new overlay path

- CHANGELOG.md
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/exec/main_test.go
Simplify passing of arguments through `wwctl container exec`. This removes the need to provide double-double dashes (e.g., `-- --`).
- Fixes #253
> Simplify passing of arguments through wwctl container exec

- CHANGELOG.md
- etc/ipxe/default.ipxe
Remove an unnecessary 3s boot from iPXE.
- Fixes #1500
> Remove an unnecessary 3s boot from iPXE

- userdocs/contents/disks.rst
Was using markdown syntax rather than rst syntax.
> Fix an href in userdocs

- CHANGELOG.md
- warewulf.spec.in
Don't package the API in RPM packages by default.
- Fixes #1493
> Don't package the API in RPM packages by default

- CHANGELOG.md
- docs/man/man5/warewulf.conf.5
- etc/warewulf.conf
- internal/pkg/config/buildconfig.go.in
- internal/pkg/config/root.go
- internal/pkg/config/root_test.go
- overlays/debug/internal/debug_test.go
- userdocs/contents/configuration.rst
CIQ is updating its training materials for Warewulf and, in so doing, we're recommending changes upstream to match. In most cases this is a filling-out of documentation to serve as reference material; but in some cases code behavior may be suggested.
- Change the default warewulfd port to `9873` to match the `warewulf.conf` and Firewalld service we've been shipping.
- Refer to `nodes.conf` as a "registry" rather than "database" in the docs.
- Remove `network` from initial `warewulf.conf`.
- Omit the `wwclient` section from `warewulf.conf` if it is empty.
> Updates from CIQ training prep

- internal/app/wwctl/node/add/main.go
- internal/app/wwctl/node/add/root.go
- internal/app/wwctl/profile/add/main.go
- internal/app/wwctl/profile/add/root.go
- internal/pkg/node/flags.go
Use `--netname=default` by default during `wwctl <node|profile> <add|set>`.
- Closes #1499
> Use "default" netname during add, set

- warewulf.spec.in
Resolve redundant file entries in `warewulf.spec`.
- Closes #1526
> Resolve redundant file entries in warewulf.spec

- userdocs/contents/configuration.rst
This was missed during the NodeInfo refactor, which also removed nodes.conf.
> Remove defaults.conf from userdocs

- CHANGELOG.md
- internal/app/wwctl/node/list/main_test.go
- internal/app/wwctl/node/set/main.go
- internal/app/wwctl/node/set/main_test.go
fix issue that --nettagdel does not work properly
- Fixes #1503
```
[root@warewulf warewulf]# wwctl node list n2 --all
NODE  FIELD                        PROFILE  VALUE
----  -----                        -------  -----
n2    Comment                      default  This profile is automatically included for each node
n2    ContainerName                default  rocky-9
n2    Init                         default  /sbin/init
n2    Ipxe                         default  default
n2    Kernel.Args                  default  quiet crashkernel=no
n2    NetDevs[default].Device      --       default
n2    NetDevs[default].Tags[dns1]  --       1.1.1.1
n2    NetDevs[default].Tags[dns2]  --       2.2.2.2
n2    NetDevs[eth1].Gateway …
```
> fix issue that --nettagdel does not work properly

- internal/app/wwctl/upgrade/config/cobra.go
`wwctl upgrade config` erroneously retained a description copied from `wwctl upgrade nodes`.
> Fix `wwctl upgrade config` description

- CHANGELOG.md
- overlays/host/internal/host_test.go
- overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
* Cherry-pick dhcp static template fix for next server #1536
* Added test for template fix
> Port next-server changes to main

- CHANGELOG.md
- overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
When using a `template: static` in the `warewulf.conf` dhcp configuration, the `dhcpd.conf.ww` template produces a `dhcpd.conf` without  a `next-server` causing (some?) iPXE clients to fail to load.
> Remove dhcp template static condition around range and next-server

- CHANGELOG.md
- etc/ipxe/default.ipxe
fix issue that initrd fails at downloading runtime overlay with permission denied error, when warewulf secure option in warewulf.conf is enabled
- Fixes #806
Before:
After:
> fix issue that initrd fails at downloading runtime overlay with permission denied error, when warewulf secure option in warewulf.conf is enabled

- CHANGELOG.md
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/provision_test.go
Although I can't reproduce the this with test, Tags are not 
awlays included in the template for e,g, grub.cfg.ww
Using a pointer to templateConfig fixes this.
> Add test for sending grub.cfg

- CHANGELOG.md
- Move #1004 change to v4.6.0
- Remove redundant v4.5.6 header
> Fix CHANGELOG for #1004

- .github/actions/generate/action.yml
- .github/actions/prepare/action.yml
- .github/actions/rpm/action.yml
- .github/workflows/documentation.yml
- warewulf.spec.in
The nightly build has been broken since the disabling of the API during RPM build. This due to gpgme-devel only being listed as required when the API was built.
This PR now lists gpgme-devel as required in all cases.
This PR also updates all workflow dependencies to their latest versions.
> Fix nightly build

- CHANGELOG.md
- internal/app/wwctl/container/exec/main.go
- internal/pkg/api/container/container.go
- internal/pkg/upgrade/node.go
Some error logs were being formatted with `%w`, which wraps errors programmatically but doesn't present errors in a straightforward format.
```
WARN   : Could not remove image files for alpine: %!w(*errors.fundamental=&{Image /var/lib/warewulf/provision/container/alpine.img of container alpine doesn't exist
0x400011d6b0})
```
> Format errors in logs as strings

- Dockerfile
- go.mod
This PR make the building of the Docker image possible again with current main branch.
Before it failed with:
```
level=error msg="Running error: context loading failed: failed to load packages: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: errors parsing go.mod:\n/warewulf-src/go.mod:3: invalid go version '1.21.0': must match format 1.23\n/warewulf-src/go.mod:5: unknown directive: toolchain\n"
make: *** [Makefile:74: lint] Error 3
```
I therefore updated the go version and ran `go mod tidy` and `go mod vendors` and then built the image with `docker build -t warewulf .`
Also the bash completion seemed outdated, so I made the copy command generic.
> Fix Dockerfile

- CHANGELOG.md
- internal/app/wwctl/overlay/build/main.go
- internal/app/wwctl/overlay/build/root.go
Remove the ability to "build" the host overlay with `wwctl overlay build`. This also obsoletes the `--nodes` flag, which is also removed.
- Closes #1419
> Remove wwctl overlay build --host

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
- internal/pkg/container/util.go
- internal/pkg/util/util.go
- userdocs/contents/containers.rst
The permissions on rootfs is part of the container image itself, and cannot reliably be used as configuration metadata by Warewulf. As such, this PR adjusts the determination of a container's readonly state to use a sentinel "readonly" file in the source dir.
- Fixes #1447
> Use a sentinel file to determine container readonly state

- .github/workflows/check.yml
- go.mod
The toolchain directive specified a newer version of the go toolchain from the go runtime used, and newer than our minimum supported.
- Fixes #1571
> Remove toolchain directive from go.mod

- CHANGELOG.md
- go.mod
- go.sum
- internal/pkg/container/imprt_test.go
Prevents a panic when importing a container from a directory containing a socket by updating containers/storage to v2.55.2, which includes https://github.com/containers/storage/pull/2117.
- Fixes #892
> Support importing containers from directories containing a socket

- warewulf.spec.in
Update `warewulf.spec.in` to package the new netplan overlay from #1463.
> Package the netplan overlay

- userdocs/contents/configuration.rst
This PR adds `firewalld` and `nftables` setup information to the `configuration.rst` file. A user recently ran into trouble with their `nftables` configuration with adding a new node and this was solved by ensuring they enabled TCP port `9873` in their `nftables` config file on the Controller Node.
- Fixes # 
- N/A
> Added firewalld and nftables setup to configuration.rst

- CHANGELOG.md
- internal/pkg/overlay/funcmap.go
- internal/pkg/overlay/overlay.go
- overlays/localtime/internal/localtime_test.go
- overlays/localtime/internal/nodes.conf
- overlays/localtime/rootfs/etc/localtime.ww
- userdocs/contents/templating.rst
- warewulf.spec.in
Add the the function softlink to the template rendering, so that
{{ softlink: "/bin/bash" }} for the file `/bin/run.ww` will create
a soft link to `/bin/bash`
It's also possible to "import" soft links from the host, e.g. the
template
{{ ImportLink "/etc/localtime" }}
set the timezone from the host.
> create soft links from overlays

- CHANGELOG.md
- Makefile
- internal/app/wwctl/configure/dhcp/root.go
- internal/app/wwctl/configure/hostfile/root.go
- internal/app/wwctl/configure/nfs/root.go
- internal/app/wwctl/configure/ssh/root.go
- internal/app/wwctl/container/copy/root.go
- internal/app/wwctl/container/rename/root.go
- internal/app/wwctl/genconf/completions/root.go
- internal/app/wwctl/genconf/man/root.go
- internal/app/wwctl/genconf/reference/root.go
- internal/app/wwctl/genconf/warewulfconf/print/root.go
- internal/app/wwctl/node/export/root.go
- internal/app/wwctl/node/list/main_test.go
- internal/app/wwctl/node/set/main_test.go
- internal/app/wwctl/overlay/chmod/root.go
- internal/app/wwctl/overlay/chown/root.go
- internal/app/wwctl/overlay/create/root.go
- internal/app/wwctl/power/root.go
- internal/app/wwctl/profile/list/main_test.go
- internal/app/wwctl/root.go
- internal/app/wwctl/upgrade/cobra.go
- internal/app/wwctl/upgrade/config/cobra.go
- internal/app/wwctl/upgrade/nodes/cobra.go
- internal/pkg/api/util/util.go
- internal/pkg/config/buildconfig.go.in
- internal/pkg/node/constructors.go
- internal/pkg/node/modifiers.go
- internal/pkg/testenv/testenv.go
- internal/pkg/warewulfd/util.go
Removes the use of init() to initialize the path to `nodes.conf`, replacing it with a dynamic lookup from config.
- Closes: #1596 
- See also: #1569
> Configure nodes.conf dynamically from config

- CHANGELOG.md
- CONTRIBUTORS.md
- userdocs/contents/boot-management.rst
In Rocky Linux 8, running the provided dracut command does not create the initramfs in a place where Warewulf is expecting it and thus fails to pull the image during the two stage boot. The fix appears to be to remove machine-id from /etc. This documentation PR reflects that
> Add note in userdoc regarding dracut and machine-id

- CHANGELOG.md
- internal/app/wwctl/container/exec/child/main.go
- internal/app/wwctl/container/exec/main.go
- internal/app/wwctl/container/exec/main_test.go
- internal/app/wwctl/container/exec/root.go
- internal/app/wwctl/container/shell/main.go
- internal/app/wwctl/container/shell/root.go
- userdocs/contents/containers.rst
Adds a `wwctl container <exec|shell> --build=false` option to prevent automatically (re)building the container.
- Closes #1490
- Closes #1489
> Add wwctl container <exec|shell> --build=false

- CHANGELOG.md
- internal/pkg/node/modifiers.go
`node.DelProfile` was erroneously operating on nodes. This pr fixes it to operate on profiles.
- Fixes: #1622
> Fix DelProfile to operate on profiles, not nodes.

- CHANGELOG.md
- userdocs/contents/dnsmasq.rst
In Rocky Linux 9, `dnsmasq` appears to default to listening on loopback only. This PR adds to the documentation that the user will need to change this to the appropriate configuration
> Update dnsmasq Documentation

- CHANGELOG.md
- dracut/modules.d/90wwinit/load-wwinit.sh
Dracut doesn't seem to always wait for the network to be as up as we might like before running the wwinit module. This PR makes the curl transfer retry up to 60 times, waiting 1s between attempts, to download images.
> adding retry to curl in wwinit dracut module

- internal/app/wwctl/overlay/build/main.go
- internal/app/wwctl/server/root.go
Fixes an invalid Umask setting during overlay build, and also makes sure that umask is 0 during warewulfd.
- Fixes: #1629
> Adjust umask during overlay build

- internal/pkg/upgrade/config.go
- internal/pkg/upgrade/node.go
Fixes a null-pointer bug in `wwctl upgrade config`.
Also removes some vestigial development-debug output.
> Fix a null-pointer bug in `wwctl upgrade config`

- internal/pkg/node/methods.go
- internal/pkg/node/methods_test.go
- internal/pkg/overlay/datastructure.go
- internal/pkg/overlay/overlay_test.go
- overlays/debug/internal/debug_test.go
Before #1628, all default constructors for nodes and profiles attempted to construct objects with pre-populated empty fields (e.g., for pointers to member structs and for collections that default to nil). Changes to MergeNode in #1629 changed this behavior intentionally to simplify the generation of minimal json; but this had the unintended side-effect of breaking existing templates that may now encounter a nil pointer, particularly when accessing member structs.
Introduced here, the Expand() methods on Node and Profile (mirroring existing Flatten() methods) are now responsible for populating such fields, and Node.Expand() is now called during template processing.
> Expand nodes when rendering overlay templates

- internal/pkg/upgrade/node.go
Removing a vesitigial `fmt.Printf` from `wwctl upgrade` which was left behind from development.
> Remove a vestigial printf from wwctl upgrade

- internal/pkg/node/fields.go
- internal/pkg/node/fields_test.go
- internal/pkg/node/mergo_test.go
- Complex values are now marshalled as json
- Booleans are now represented as truth values
- Fixes https://github.com/warewulf/warewulf/pull/1568#issuecomment-2602073925
> Enhancements for node.Field formatting

- CHANGELOG.md
- overlays/issue/internal/issue_test.go
- overlays/issue/internal/nodes.conf
- overlays/issue/rootfs/etc/issue.ww
Fix a newline handling in /etc/issue.
Previous behavior:
Note how the kernel version and args are all on the same line.
> Fix newline handling in /etc/issue

- CHANGELOG.md
- etc/ipxe/dracut.ipxe
During migration of our cluster to warewulf we ran into an issue with dracut and ib. Our nodes are using infiniband exclusively with only ipmi being served over ethernet. It seems that dracut (without ip= defined) will attempt to configure the first interface using dhcp and no others. In our environment this results in dracut boots failing to actually pull down containers as the ib interface isn't configured.
This PR adds an additional ```ip=``` argument for each configured interface in addition to the already present ```ifname=``` argument to the kernel cmdline.
- Fixes #1620
> have dracut explicitly configure defined interfaces

- .devcontainer/devcontainer.json
- CHANGELOG.md
- userdocs/contributing/development-environment-devcontainer.rst
- userdocs/index.rst
Add preliminary Development Containers support for VSC (https://containers.dev/)
Based on a Rocky9 container and includes the following features.
* common-utils (creates vscode user)
* go toolchain (latest)
* makefile support
Lightly tested but will build and `make test` in a Dev Container.  This is a dev feature so no CHANGELOG added.
> Add Dev Container support

- internal/app/wwctl/image/copy/main_test.go
- internal/app/wwctl/image/exec/main_test.go
- internal/pkg/image/config.go
Previous name (before #1641) was "container." New name (from #1641) was "image" but a plural name seems better.
> Change image provision directory to "images"

- CHANGELOG.md
- internal/app/wwctl/node/add/main_test.go
- internal/pkg/node/datastructure.go
- internal/pkg/node/fields_test.go
- internal/pkg/node/mergo_test.go
- internal/pkg/node/methods_test.go
- internal/pkg/overlay/overlay_test.go
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
- internal/pkg/warewulfd/provision.go
- overlays/debug/internal/nodes.conf
- overlays/debug/rootfs/tstruct.md.ww
- overlays/issue/internal/nodes.conf
- overlays/issue/rootfs/etc/issue.ww
Refactor kernel args as a slice (list) rather than a single string. This lets kernel arguments from profiles be inherited and added to by other profiles and nodes.
> Refactor kernel args as a slice

- userdocs/contributing/contributing.rst
New slack link is https://join.slack.com/t/warewulf/shared_invite/zt-2yer2fd5y-7rC2r1kBVyGHwQf4VJwzHA
- Close: #1651
> updated slack link

- CHANGELOG.md
- etc/nodes.conf
The default `etc/nodes.conf` has not been upgraded to use the kernel args list (not string). This PR updates the default.
Without it, the default install gives
``console
vscode ➜ /workspaces/warewulf (tm-make-install) $ wwctl node list
ERROR: yaml: unmarshal errors:
line 24: cannot unmarshal !!str `quiet c...` into []string
```
> Fix default nodes.conf to use the new kernel command line list format

- CHANGELOG.md
- Variables.mk
When doing a `make install` on systems where `sudo` does not pass the `PWD` environment variable the dependency paths are mangled.  This occurs in the `godeps` in `Variables.mk` due to the empty `$PWD` in the `sed` function. 
- Fixes #1660
> Fix make install when sudo does not set PWD

- CHANGELOG.md
- internal/pkg/power/ipmitool.go
Just passing the command that is returned from expanding the bmc template to `sh -c` rather than trying to execute itself. Pro's and cons, but the target community won't have problems with this being evaluated as a shell command (where e.g. env variables are honored).
Disclaimer: didn't test yet, no update to test-suite 
- Fixes #1663
> Use sh to parse and exec IPMI command (fixes #1663)

- CHANGELOG.md
- internal/app/wwctl/node/list/main_test.go
- internal/pkg/node/constructors_test.go
- internal/pkg/node/mergo.go
- internal/pkg/node/mergo_test.go
- internal/pkg/node/methods.go
The new `MergeNode` code broke support for slice element negation for fields other than "profiles." This PR restores that functionality.
- Fixes: #1677
> Fixed negation for slice field elements during profile/node merge

- CHANGELOG.md
- userdocs/contents/nodeconfig.rst
Turns out we already support commas in list values by enclosing the value in quotes.
```
? Are you sure you want to modify 1 profile(s)? [y/N] y█
default  Kernel.Args               quiet,crashkernel=no,nosplash,console=ttyS0,115200
```
- Closes: #1679
> Document commas in kernel arguments

- CHANGELOG.md
- internal/app/wwctl/node/add/root.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/overlay/build/root.go
- internal/app/wwctl/overlay/chmod/root.go
- internal/app/wwctl/overlay/chown/root.go
- internal/app/wwctl/overlay/delete/root.go
- internal/app/wwctl/overlay/edit/root.go
- internal/app/wwctl/overlay/imprt/root.go
- internal/app/wwctl/overlay/list/main.go
- internal/app/wwctl/overlay/list/root.go
- internal/app/wwctl/overlay/show/root.go
- internal/app/wwctl/profile/add/root.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/overlay/overlay.go
- internal/pkg/overlay/overlay_test.go
When an overlay exists as both a distribution and a site overlay, only show the overlay in the list once.
- Fixes #1675
> Show each overlay only once

- CHANGELOG.md
- internal/app/wwctl/image/exec/main.go
> Remove a redundant "Building image" log message after image exec

- CHANGELOG.md
- internal/pkg/node/mergo_test.go
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
NetDev defaults don't behave quite the same as standard fields, because they need to be set per-device. Meanwhile, trying to set a value may erroneously override values that are on the default profile.
Switch this to a warning rather than attempting to take explicit action.
- Closes: #1661
> Don't populate NetDevs[].Type or NetDevs[].Netmask during upgrade

- CHANGELOG.md
- internal/pkg/node/mergo.go
- internal/pkg/node/mergo_test.go
getNodeProfiles was misordering nested profiles, leading to child values taking precedence over parent values.
- Fixes: #1672
> Prefer parent profile values over child profile values

- CHANGELOG.md
- internal/app/wwctl/upgrade/config/cobra.go
- internal/app/wwctl/upgrade/nodes/cobra.go
`wwctl upgrade` copies outputFile to outputFile-old before over-writing; but it was trying to do this even when outputFile didn't exist, causing an error.
- Fixes: #1671
> Don't attempt to back-up an output file that doesn't exist during upgrade

- CHANGELOG.md
- internal/app/wwctl/node/list/main_test.go
- internal/pkg/api/node/list.go
The yaml and json output from `wwctl node list` was a simple list of nodes, which did not include the node name / id. This builds a map keyed by the node id and returns that in stead.
- Fixes: #1667
> wwctl node list <--yaml|--json> outputs a map keyed by node name

- CHANGELOG.md
- overlays/wwinit/rootfs/init
systemd mounts /run itself (and does so redundantly if we do); and it appears we don't depend on /run for anything during wwinit.
Meanwhile, I'm cleaning up the other mounts so they're a bit more reliable.
- Fixes: #1566
> Don't mount /run during wwinit

- CHANGELOG.md
- internal/pkg/image/initramfs.go
- internal/pkg/warewulfd/provision.go
> Fix a panic in warewulfd when no kernel fields are specified

- CHANGELOG.md
- internal/app/wwctl/overlay/imprt/main.go
- internal/pkg/overlay/overlay.go
Sets execute permissions on directories during `wwctl overlay import --parents` to match read permissions from the source.
- Fixes: #1655
> Set execute permissions for intermediate directories

- CHANGELOG.md
- internal/app/wwctl/overlay/edit/main.go
> Create temporary files in overlay directory during `wwctl overlay edit`

- CHANGELOG.md
- internal/pkg/node/mergo.go
- internal/pkg/node/mergo_test.go
The custom mergo transformer was merging zero-value `net.IP` fields over-top of non-zero `net.IP` fields. This had the result (for example) that a zero-value netmask field on a node took precedence over a non-zero netmask field from a profile.
This PR causes zero `net.IP` values to be skipped during merge.
- Fixes: #1710
> Prevent merging of zero-value net.IP fields

- CHANGELOG.md
- dracut/modules.d/90wwinit/load-wwinit.sh
- dracut/modules.d/90wwinit/parse-wwinit.sh
- internal/pkg/warewulfd/provision.go
Urlencode the asset tag during dracut boot.
- Fixes: #1610
> Urlencode asset keys during dracut boot

- CHANGELOG.md
- etc/warewulf.conf
- internal/pkg/config/ssh.go
- internal/pkg/configure/ssh.go
- overlays/debug/internal/debug_test.go
- overlays/host/internal/host_test.go
- userdocs/contents/configuration.rst
- Re-orders ssh key types so that ed25519 is first, which causes it to be used by default.
- Builds the host overlay as part of `wwctl configure ssh`.
- Fixes: #981
> Re-order SSH key types to make ed25519 default

- CHANGELOG.md
- docs/man/man5/warewulf.conf.5
- etc/warewulf.conf
- include/systemd/warewulfd.service.in
- internal/app/wwctl/overlay/show/main_test.go
- internal/pkg/config/buildconfig.go.in
- internal/pkg/config/root_test.go
- internal/pkg/upgrade/config.go
- internal/pkg/upgrade/config_test.go
- internal/pkg/warewulfd/daemon.go
- overlays/debug/internal/debug_test.go
- overlays/debug/rootfs/tstruct.md.ww
- overlays/fstab/internal/warewulf.conf
- overlays/host/internal/warewulf.conf
- overlays/host/internal/warewulf.conf-static
- overlays/hosts/internal/warewulf.conf
- overlays/wwinit/internal/warewulf.conf
- overlays/wwinit/internal/wwinit_test.go
- userdocs/contents/configuration.rst
- userdocs/contents/troubleshooting.rst
- userdocs/contributing/development-environment-vagrant.rst
- userdocs/quickstart/debian12.rst
- userdocs/quickstart/el.rst
- userdocs/quickstart/suse15.rst
Removes the syslog configuration to send all log data to stdout/stderr (for receipt by the systemd journal).
- Fixes: #1606
> Remove `warewulf.conf:syslog`

- CHANGELOG.md
- etc/warewulf.conf
Add a default for the dhcp.template variable used in dhcp.conf.  This removes hacks out of the OpenHPC recipe for Warewulf since configuration is done through `sed` scripts and adding a line is a bit fragile/extra step.
```yaml
dhcp:
template: dynamic
```
> Set default for dhcp.template in warewulf.conf

- CHANGELOG.md
- overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
If `.Network` and `.Netmask` are defined, generate the subnet.
If `.RangeStart` and `.RangeEnd` are defined, generate the dynamic range.
If `.Ipaddr` is defined, generate "next-server".
This makes it possible to disable just the dynamic range without losing access to the next-server required by static host entries.
- Closes: #1469
> Generates as much of the DHCP subnet as possible

- CHANGELOG.md
- internal/app/wwctl/flags/flags.go
- internal/app/wwctl/node/add/root.go
- internal/app/wwctl/node/set/root.go
- internal/app/wwctl/profile/add/root.go
- internal/app/wwctl/profile/set/root.go
- internal/pkg/node/datastructure.go
- userdocs/contents/overlays.rst
Updated overlay flags
New flags: `wwctl <node|profile> <add|set> [--runtime-overlays|--system-overlays]`.
Previous flags retained hidden, deprecated for backwards-compatibility.
Also marked `--container` flag deprecated, because this syntax wasn't applied when the container -> image refactor was done.
- Closes: #1495
> Update overlay flags for clarity

- CHANGELOG.md
- internal/app/wwctl/overlay/show/main.go
- internal/app/wwctl/overlay/show/main_test.go
Look for an overlay template with a `.ww` suffix if the specified file has no `.ww` suffix and does not exist.
- Closes: #649
> Make .ww suffix optional during wwctl overlay show --render

- CHANGELOG.md
- etc/nodes.conf
- internal/app/wwctl/image/build/main.go
- internal/app/wwctl/image/build/root.go
- internal/app/wwctl/image/exec/main.go
- internal/app/wwctl/image/syncuser/main.go
- internal/app/wwctl/image/syncuser/root.go
- internal/pkg/api/image/image.go
- internal/pkg/image/syncuser.go
- internal/pkg/overlay/funcmap.go
- internal/pkg/overlay/funcmap_test.go
- internal/pkg/overlay/overlay.go
- overlays/syncuser/internal/nodes.conf
- overlays/syncuser/internal/syncuser_test.go
- overlays/syncuser/rootfs/etc/group.ww
- overlays/syncuser/rootfs/etc/passwd.ww
- userdocs/contents/images.rst
- userdocs/contents/ipmi.rst
- userdocs/contents/nodeconfig.rst
- userdocs/contents/overlays.rst
- userdocs/contents/setup.rst
- userdocs/contents/templating.rst
This change is the overall "make syncuser emphatically optional, opt-in." Mostly I see syncuser cause confusion for people who think you have to do it, rather than people who chose to use it. So this intends to not do any syncuser by default, and then document how to use it if you need it.
- Fixes #1321 
- Fixes #829
- Fixes #1322
> syncuser improvements

- CHANGELOG.md
- Makefile
- userdocs/quickstart/el.rst
- warewulf.spec.in
@anderbubble simply checkout this PR and run `make help`
I would like to have this in 4.6.0 (as it doesn't have any functionality) and can 
you document the targets I forgot?
Stolen from the Schedmd people without any shame as syncuser creates so much
pain which we need only for munge
> create commandline options for Makefile

- CHANGELOG.md
- internal/pkg/configure/dhcp.go
The DHCP range was made optional in the template, but I had missed that it is required by `wwctl configure dhcp`. This PR removes it from that code.
> Make DHCP range optional

- CHANGELOG.md
- etc/nodes.conf
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
Adds fstab resources for `/home` and `/opt` to the initial default profile, and to the default profile during an upgrade if requested.
- Fixes #1744
> Default nfs resources

- CHANGELOG.md
- internal/pkg/overlay/overlay.go
Previously, `wwctl overlay build` generated info logs that included the full list of overlays included in each overlay image. But, now that overlay lists are long, even by default, these logs got very long and difficult to read.
This PR reduces the default verbosity for system and runtime overlays. Previous output moved to `--debug`.
> Reduced default verbosity of `wwctl overlay build`

- CHANGELOG.md
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
Fixes an issue where `wwctl upgrade nodes` applied default NFS mounts and ported in NFS entries from warewulf.conf.
- Closes: #1758
> Port NFS exports before applying defaults

- .github/workflows/nightly-release.yml
- CHANGELOG.md
Fixes nightly builds.
Fixes a bug where the GitHub action checkout does not unzip the `.github` directory when not using git.  This is required to use the `.github/actions/rpm` action.
> Install git before checkout

- CHANGELOG.md
- internal/pkg/image/initramfs.go
- internal/pkg/image/initramfs_test.go
Ubuntu dracut generates names like `/boot/initrd.img-*` which wasn't caught by the pattern we were already using.
This PR adds that pattern to the dracut search path and adds a test for it.
> Add support for ubuntu-style dracut image names

- CHANGELOG.md
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
We changed the default kernel args in `nodes.conf` but not in what is generated by `wwctl upgrade nodes`. This PR synchronizes them.
> Change upgraded default kernel args to match distributed `nodes.conf`

- CHANGELOG.md
- internal/app/wwctl/overlay/build/main.go
- internal/app/wwctl/overlay/build/root.go
- internal/app/wwctl/overlay/imprt/main.go
- internal/app/wwctl/overlay/imprt/root.go
Use `wwctl overlay <import|build> --workers=0` to indicate default value.
By default, uses `runtime.NumCPU()`
The default value is rendered in the generated man pages, which made their content dependent on build system characteristics.
> Use `wwctl overlay <import|build> --workers=0` to indicate default value

- CHANGELOG.md
- Makefile
- Variables.mk
- include/sos/warewulf.py
- userdocs/troubleshooting/troubleshooting.rst
- warewulf.spec.in
_This is a replacement for PR #1761, which was closed due to the accidental deletion of the original fork_
New `sosreport` plugin added as separate RPM
This PR adds Warewulf support to [sosreport](https://github.com/sosreport/sos). `sosreport` is a tool to collect data for troubleshooting issues on Enterprise Linux distributions. This PR adds a Warewulf plugin that collects data from Warewulf directories, including the configuration, and captures output from several `wwctl` commands. The GitHub workflow for tagged releases has been updated to generate a separate RPM package compatible with both EL8 and EL9 distros.
I considered not including the `wwctl` commands directly since all the data is already available in `/etc/warewulf/`. However, the commands contribute very little in terms of …
> Adding New SOS Plugin

- Dockerfile
Dockerfile needs a fix, because go1.22 is required for docker build; with go1.21 it bails out early on.
- Fixes a bug blocking the docker build process
If the above is a MUST, let's expand on this PR to get things going...
> fix Dockerfile: go1.22 is required for docker build

- CHANGELOG.md
- internal/pkg/node/fields.go
- internal/pkg/node/mergo_test.go
v4.6.0 broke the display of dotted Tags and NetDevs, like `NetDev[eth0.100]` or `Tags[My.Tag.Name]` by always splitting on `.`, even when inside a bracketed expression.
This PR fixes that behavior by only splitting on `.` when not in a `[ ]` portion of the name.
Thanks to @atopion for the first pass at a fix, and for reporting the issue.
- Fixes: #1825
> Fix display of dotted field names

- CHANGELOG.md
- internal/app/wwctl/overlay/imprt/main.go
- internal/app/wwctl/overlay/imprt/main_test.go
- internal/app/wwctl/overlay/imprt/root.go
- internal/pkg/util/copyfile.go
Allow files imported into an overlay to be overwritten if they exist.  Updates `wwctl overlay import` documentation to reflect current options.
This enables the use of sed/awk workflows for overlay files, for example:
```bash
./wwctl overlay cat test /test.txt | sed -e 's/9/1/' | sudo ./wwctl overlay import test --overwrite /dev/stdin /test.txt
```
- closes #386
> Add `--overwrite` to `wwctl overlay import`

- userdocs/overlays/overlays.rst
- userdocs/server/bootloaders.rst
- userdocs/server/installation.rst
- Document using mock to build RPMs
- Clarify installing warewulf-dracut in the image
- Fix vestigial references to v4.6.0rc2
- Add a warning about using `PasswordlessRoot`
- Closes: #1767
- Closes: #1769
> Various minor documentation updates

- userdocs/nodes/network.rst
The network bonding documentation had a yaml document with improper indentation.
https://warewulf.org/docs/v4.6.x/nodes/network.html#bonding
This fixes the indentation.
> Fix yaml indentation in network bond example

- CHANGELOG.md
- internal/app/wwclient/root.go
- internal/app/wwctl/configure/root.go
- internal/app/wwctl/image/delete/root.go
- internal/app/wwctl/image/list/root.go
- internal/app/wwctl/image/root.go
- internal/app/wwctl/node/edit/root.go
- internal/app/wwctl/node/export/root.go
- internal/app/wwctl/node/list/root.go
- internal/app/wwctl/node/root.go
- internal/app/wwctl/node/status/root.go
- internal/app/wwctl/overlay/build/root.go
- internal/app/wwctl/overlay/list/root.go
- internal/app/wwctl/overlay/root.go
- internal/app/wwctl/power/root.go
- internal/app/wwctl/profile/add/root.go
- internal/app/wwctl/profile/edit/root.go
- internal/app/wwctl/profile/list/root.go
- internal/app/wwctl/profile/root.go
- internal/app/wwctl/profile/set/root.go
- internal/app/wwctl/root.go
Explicitly enforce the number or arguments accepted by some `wwctl` subcommands
- Closes: #1717
> Explicitly enforce the number or arguments accepted by some `wwctl` subcommands

- CHANGELOG.md
- internal/pkg/overlay/overlay.go
- internal/pkg/warewulfd/provision.go
- overlays/wwinit/rootfs/warewulf/wwprescripts
- If `init` is not specified, wwinit looks for /sbin/init, /etc/init, and /bin/init, matching dracut behavior.
- assume ipxe template=default if not set
- Display a warning during overlay build if an overlay list is empty
- Closes: #1808
- Closes: #1813
> Restore some default behaviors

- CHANGELOG.md
- etc/grub/grub.cfg.ww
The grub network boot configuration had several places where it intended to sleep to display an error message and then reboot; but the sleep and reboot code was missing.
- Closes: #1791
> Add indicated sleep and reboot during grub boot

- CHANGELOG.md
- CONTRIBUTORS.md
- internal/app/wwctl/node/imprt/main.go
- internal/app/wwctl/node/imprt/main_test.go
- internal/app/wwctl/node/imprt/root.go
- internal/pkg/api/node/edit.go
Check if node exists, if not add it first before
attempting SetNode().
Fixes: #1842
Currently `wwctl node import /some/yaml` that contains new node entries fails. This appears to be because the NodeAddFromYaml function only calls SetNode, which expects a node id to already exist in the node db (nodes.conf). This PR adds the code to check if the node exists, if not, add it first before calling SetNode.
- Fixes #1842
> fix import from yaml where node does not pre-exist

- CHANGELOG.md
- overlays/wwinit/rootfs/warewulf/config.ww
- overlays/wwinit/rootfs/warewulf/init.d/50-ipmi
- userdocs/nodes/ipmi.rst
Set an IPMI tag ``vlan`` to configure the vlan during ``ipmiwrite``
- Closes: #1031
> Set an IPMI tag ``vlan`` to configure the vlan during ``ipmiwrite``

- CHANGELOG.md
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
- internal/pkg/upgrade/slices.go
`wwctl upgrade nodes --replace-overlays` avoids applying overlays multiple times
- Closes: #1823
> wwctl upgrade nodes --replace-overlays avoids applying overlays multiple times

- CHANGELOG.md
- internal/app/wwctl/node/list/main_test.go
- internal/pkg/api/node/list.go
Fix a panic during `wwctl node list --ipmi` for nodes with no ipmi configuration.
- Fixes #1847
> Fix a panic during `wwctl node list --ipmi` for nodes with no ipmi configuration.

- CHANGELOG.md
- etc/nodes.conf
- internal/pkg/upgrade/node.go
- internal/pkg/upgrade/node_test.go
Fix regression that net.ifnames=1 was missing in the kernel command line, which forces SUSE udev to default behavior
> fix SUSE specific udev regression

- CHANGELOG.md
- Makefile
- dracut/modules.d/90wwinit/module-setup.sh
- dracut/modules.d/90wwinit/nm-wait-online-initrd.service.override
While discussing #1800 the underlying cause of dracut not necessarily waiting for configured interfaces to actually be up was found. This PR adds an ```override.conf``` when the ```systemd``` and ```network-manager``` modules are included in dracut for the ```nm-online-wait-initrd.service``` unit that removes the ```-s``` argument to the ```nm-online``` invocation in that unit. ```nm-online -s``` returns once ```NetworkManager``` is up and configuration for defined interfaces is requested but not necessarily when interfaces are fully configured and up. This change should make ```nm-online``` wait until the timeout is reached (300s in this pr) or configured interfaces are actually up.
> Make nm-wait-online-initrd.service wait for interfaces to be online during dracut boot

- .github/actions/rpm/action.yml
Seemed like a typo. No changelog.
- Fixes # N/A
> Fix typo in rpm github action

- CHANGELOG.md
- overlays/wwinit/rootfs/init
Fixed a regression in SELinux support by restoring the `/run` mount during wwinit.
https://systemd.io/INITRD_INTERFACE/
- Fixes: #1910
> Fixed a regression in SELinux support by restoring the `/run` mount during wwinit

- CHANGELOG.md
- userdocs/nodes/nodes.rst
This PR adds a very basic overview on how to use `wwctl node import` for both CSV and YAML files. There is a note about a current bug that prevents CSV importing.
> Update documentation to include instruction for using wwctl node import

- CHANGELOG.md
- internal/app/wwctl/image/shell/root.go
Make `wwctl image shell --help` fit within 80 columns.
> Fix width of wwctl image shell --help

- CHANGELOG.md
- internal/app/wwctl/overlay/edit/main.go
Simplifies copying edited tmpfile back to original location, which also preserves permissions from the original file during the edit.
- Fixes: #1886
> Preserve file permissions during wwctl overlay edit

- CHANGELOG.md
- userdocs/nodes/network.rst
- userdocs/overlays/overlays.rst
> Additional nettag documentation in userdocs

- CHANGELOG.md
- internal/pkg/overlay/config.go
- internal/pkg/overlay/overlay.go
- internal/pkg/overlay/overlay_test.go
- internal/pkg/util/util.go
- internal/pkg/util/util_test.go
- internal/pkg/warewulfd/api/api.go
- internal/pkg/warewulfd/api/image_test.go
- internal/pkg/warewulfd/api/node.go
- internal/pkg/warewulfd/api/node_test.go
- internal/pkg/warewulfd/api/overlay.go
- internal/pkg/warewulfd/api/overlay_test.go
- internal/pkg/warewulfd/api/profile.go
- internal/pkg/warewulfd/api/profile_test.go
- Added system and runtime overlay built time.
- Support If-None-Match header in `PUT /api/nodes/{id}`
- Added `PUT|DELETE /api/overlays/{name}/file?path={path}`
- Added `DELETE /api/overlays/{name}/file?path={path}`
- Restore default idempotency of `PUT /api/nodes/{id}`
- `DELETE /api/overlays/{name}?force=true` can delete overlays that are in use
> additions to wwapi

- CHANGELOG.md
- cmd/wwctl/main.go
- internal/pkg/image/imprt.go
The containers/storage library uses a "reexec" pattern where it spawns subprocesses of itself to perform certain operations (like unpacking archives in chroot environments). When it does this, it expects the main() function to have called reexec.Init() to register handlers for these subprocess operations.
This was previously done targeting image imports. This fix moves the init to the beginning of wwctl to cover all possible cases within the command.
- Fixes: #1879
> Move reexec.Init() to beginning of wwctl

- CHANGELOG.md
- overlays/fstab/internal/fstab_test.go
- overlays/fstab/internal/nodes.conf
- overlays/fstab/rootfs/etc/fstab.ww
- overlays/ignition/internal/ignition_test.go
- overlays/ignition/rootfs/etc/systemd/system/ww4-mounts.ww
Update fstab and ignition overlays to properly handle overlays specified in a scalar, comma-separated string, when expected.
- Fixed: #1950
> Fixed handling of comma-separated mount options in fstab and ignition overlays

- CHANGELOG.md
- internal/app/wwctl/overlay/edit/main.go
Switches to using sha256 rather than mtime to detect changes to an overlay file.
- Fixes: #1947
> Fix a race condition in wwctl overlay edit

- CHANGELOG.md
- warewulf.spec.in
This error was apparently being ignored by rpmbuild; but it was called out by Copilot during a recent review.
> Fix a syntax error in the RPM specfile

- CHANGELOG.md
- CONTRIBUTORS.md
- etc/grub/grub.cfg.ww
- etc/ipxe/default.ipxe
- internal/pkg/warewulfd/parser.go
- internal/pkg/warewulfd/parser_test.go
- internal/pkg/warewulfd/provision.go
- internal/pkg/warewulfd/provision_test.go
Add preliminary/partial support for booting nodes via IPv6 PXE. This PR does not provide full IPv6 provisioning support, however, I believe the only thing missing is DHCP server support.  
Tested with Rocky9 on aarch64 on MacOS with QEMU.  Rocky9 iPXE did not work with IPv6, building iPXE from git fixed it.
Detailed Changes:
* This PR is based off of #1852 (rebased)
* Introduces a new provisioning (iPXE) template variable `Authority` which combines the IP address and port and provides the `[]` if the address is IPv6 according to RFC 3986.
* The value of Authority is set to the same address family as the requesting IP.  This can be used in a template regardless of address family.
* Unit tests added for parsing and Authority.
* default.ipxe has been updated and tested with Authority.
* Now …
> Add IPv6 support for iPXE booting

- CHANGELOG.md
- cmd/wwclient/main.go
- internal/app/wwclient/root.go
- internal/pkg/pidfile/pidfile.go
- userdocs/nodes/disks.rst
Update wwclient such that each file in the runtime overlay is applied atomically.
Also adds --once flag to allow wwclient to be run one time.
- Closes: #1307
- Closes: #1975
- Closes: #1226
> Atomic overlay file application in wwclient

- .devcontainer/devcontainer.json
- .github/workflows/release.yml
- CHANGELOG.md
- Makefile
- overlays/host/internal/host_test.go
- overlays/host/rootfs/etc/dnsmasq.d/ww4-hosts.conf.ww
- warewulf.spec.in
Add support for EL10
* Update `.spec` to depend on `dnsmasq` and not `dhcpd-server` for EL10
* Add make rpm and version targets to the makefile
* Use `tmpfile` for `make dist` to support building in a devcontainer with colima on a mac.
* Update CI/CD to get the version via `make version` to support multiple directories in the mock build process (glob returns multiple directories in the `make -C` in `release.yml`.
* Update CI/CD to use Rocky 10 build container.
* Update CI/CD to add EL10 target
* Update CI/CD to use `make version` information for mock
* Updated .devcontainer to Rocky 10
Only tested on a manual trigger.
> Add support for EL10

- CHANGELOG.md
- etc/warewulf.conf
Adds 'warewulfd' to 'systemd name' key in 'warewulf' in warewulf.conf
Without this set warewulfd is not restarted with `wwctl configure --all`
This is the warning produced without the key.
```
WARN   : Not (re)starting Warewulf server: no systemd name configured
```
> Add default for systemd name for warewulf in warewulf.conf

- CHANGELOG.md
- warewulf.spec.in
Update the rpm specfile BuildRequires to match go.mod for the required Go version.
- Fixes: #1990
> Update golang BuildRequires in warewulf.spec.in

- CHANGELOG.md
- warewulf.spec.in
brp-mangle-shebangs has been changing shebang lines in overlays, including changing `/bin/sh` to `/usr/bin/sh`. This is probably not the right thing for overlays, at least, since we don't actually know that the system being booted has moved things to `/usr/`.
> Exclude overlays from brp-mangle-shebangs
