Makefile
etc/hosts.tmpl
etc/warewulf.conf
internal/app/wwctl/configure/dhcp/main.go
internal/app/wwctl/configure/hosts/main.go
internal/app/wwctl/configure/hosts/root.go
internal/app/wwctl/configure/nfs/main.go
internal/app/wwctl/configure/nfs/root.go
internal/app/wwctl/configure/root.go
internal/app/wwctl/configure/ssh/main.go
internal/app/wwctl/container/exec/child/main.go
internal/pkg/node/datastructure.go
internal/pkg/overlay/funcmap.go
internal/pkg/warewulfconf/constructors.go
internal/pkg/warewulfconf/datastructure.go
overlays/runtime/default/etc/hosts.ww
overlays/system/default/etc/ssh/ssh_host_dsa_key.pub.ww
overlays/system/default/etc/ssh/ssh_host_dsa_key.ww
overlays/system/default/etc/ssh/ssh_host_ecdsa_key.pub.ww
overlays/system/default/etc/ssh/ssh_host_ecdsa_key.ww
overlays/system/default/etc/ssh/ssh_host_ed25519_key.pub.ww
overlays/system/default/etc/ssh/ssh_host_ed25519_key.ww
overlays/system/default/etc/ssh/ssh_host_rsa_key.pub.ww
overlays/system/default/etc/ssh/ssh_host_rsa_key.ww
overlays/system/default/init.ww

This is still a work in progress, need to finish fleshing out NFS configure.

Configure additions

---

README.md

A fix related to #11. Does this look better now?

Fix README.md related to issue #11.

---

README.md
docs/README.md
docs/rhel7-quickstart.md
docs/rhel8-quickstart.md
internal/app/wwctl/configure/ssh/main.go
internal/app/wwctl/node/set/main.go
internal/app/wwctl/node/set/root.go
internal/app/wwctl/profile/set/main.go
internal/app/wwctl/profile/set/root.go
internal/pkg/node/constructors.go
overlays/system/default/init
overlays/system/default/warewulf/wwinit

Added kernel args to node and profile set, set sane defaults, and updated init sequences

Various fixups

---

internal/app/wwctl/node/list/main.go
internal/app/wwctl/node/set/main.go
internal/app/wwctl/profile/list/main.go
internal/app/wwctl/profile/set/main.go
internal/pkg/node/constructors.go

Cleaned up the node and profile set commands and moved the node and profile list sorting to the main constructor.

Various Cleanups

---

overlays/system/default/warewulf/init.d/50-ipmi

This is just a minor IPMI fix in the node init script.

Minor IPMI fix

---

go.mod
go.sum
internal/app/wwctl/container/imprt/main.go
internal/app/wwctl/kernel/imprt/main.go
internal/app/wwctl/node/set/main.go
internal/app/wwctl/profile/set/main.go
internal/app/wwctl/server/reload/main.go
internal/app/wwctl/server/reload/root.go
internal/app/wwctl/server/restart/main.go
internal/app/wwctl/server/restart/root.go
internal/app/wwctl/server/root.go
internal/pkg/warewulfconf/constructors.go
internal/pkg/warewulfd/daemon.go
internal/pkg/warewulfd/ipxe.go
internal/pkg/warewulfd/nodedb.go
internal/pkg/warewulfd/util.go
internal/pkg/warewulfd/warewulfd.go

Warewulfd fixups to automatically cache the node database and reload configuration automatically as well as when requested.

Warewulfd fixes

---

docs/docs/about/templating.md
internal/pkg/overlay/overlay.go

I added two functions for in- and decrementing variables in templates.
Also added some very basic documentation with rudimentary examples.

additional functions for templates

---

internal/app/wwctl/node/set/main.go

SetType was twice in `app/wwctl/node/set/main.go` --> removed

removed duplicate SetType

---

internal/app/wwctl/node/add/main.go
internal/app/wwctl/node/add/root.go
internal/app/wwctl/node/delete/root.go

There were a few inconstant parameters in `wwctl node {add, del}`
I removed `group` and `controller`, both didn't do anything. I added `clusterName` to `wwctl node add`.
Also, the printouts in debug-mode were broken, so I fixed them too.

Node cleanup

---

Makefile
cmd/bash_completion/bash_completion.go
cmd/man_page/man_page.go
cmd/wwctl/main.go
internal/app/wwctl/root.go
internal/pkg/node/datastructure.go
internal/pkg/warewulfconf/datastructure.go

Added bash-completion for wwctl

Bash completion

---

internal/app/wwctl/container/exec/child/main.go
internal/app/wwctl/container/imprt/main.go
internal/pkg/util/util.go

Container resolv.conf optimizations

---

internal/app/wwctl/container/exec/child/main.go

Seems to be extra test code from https://github.com/hpcng/warewulf/pull/112/commits/09a83ff90400dd5703da740b9072ecf9e792e070.

Remove commented test code

---

internal/app/wwctl/kernel/imprt/main.go
internal/app/wwctl/overlay/chown/main.go
internal/pkg/oci/cache.go

Missed a few lint errors, fixed now.

Lint fixes

---

.github/workflows/lint.yaml

Increase timeout for lint action

---

internal/app/wwctl/server/reload/main.go
internal/app/wwctl/server/restart/main.go
internal/app/wwctl/server/start/main.go
internal/app/wwctl/server/status/main.go
internal/app/wwctl/server/stop/main.go
internal/pkg/warewulfd/container.go
internal/pkg/warewulfd/daemon.go
internal/pkg/warewulfd/ipxe.go
internal/pkg/warewulfd/kernel.go
internal/pkg/warewulfd/kmods.go
internal/pkg/warewulfd/nodedb.go
internal/pkg/warewulfd/runtime.go
internal/pkg/warewulfd/system.go
internal/pkg/warewulfd/util.go
internal/pkg/warewulfd/warewulfd.go

Adding timestamps per issue request #121.

Adding timestamps to log output

---

internal/app/wwctl/node/list/main.go
internal/app/wwctl/node/set/main.go
internal/app/wwctl/profile/list/main.go
internal/app/wwctl/profile/set/main.go
internal/pkg/node/constructors.go

A few minor changes as I was going through the documentation refactor.

Updates for docs

---

internal/pkg/kernel/kernel.go

Revert "allow compressed kernels with gz suffix"

---

internal/pkg/kernel/kernel.go
internal/pkg/util/util.go

An implementation of PR #120 for issue #119.

Arm kernel support

---

internal/app/wwctl/overlay/build/main.go
internal/app/wwctl/overlay/build/root.go
internal/pkg/kernel/kernel.go
internal/pkg/util/util.go

Overlay fixes

---

internal/app/wwctl/kernel/imprt/main.go
internal/app/wwctl/kernel/list/main.go
internal/pkg/kernel/kernel.go

version is also stored, kernel name defaults to its version

handling kernels by name

---

overlays/system/default/init

Fix sh syntax for equal operator

---

containers/Singularity/centos-8.def
containers/Singularity/rocky-8.def

A offering from Bill Comisky in Slack to ensure that nodes boot network predictably for EL8 varients.

Make sure that ifcfg-XXXX files work properly

---

etc/dhcp/default-dhcpd.conf
etc/warewulf.conf
internal/app/wwctl/overlay/chmod/main.go
internal/app/wwctl/overlay/chmod/root.go
internal/app/wwctl/overlay/chown/main.go
internal/app/wwctl/overlay/chown/root.go
internal/app/wwctl/overlay/create/main.go
internal/app/wwctl/overlay/create/root.go
internal/app/wwctl/overlay/delete/main.go
internal/app/wwctl/overlay/delete/root.go
internal/app/wwctl/overlay/edit/main.go
internal/app/wwctl/overlay/edit/root.go
internal/app/wwctl/overlay/mkdir/main.go
internal/app/wwctl/overlay/mkdir/root.go
internal/app/wwctl/server/start/main.go
internal/pkg/overlay/overlay.go
internal/pkg/warewulfconf/constructors.go
internal/pkg/warewulfconf/datastructure.go
internal/pkg/warewulfconf/modifiers.go
internal/pkg/warewulfd/runtime.go
internal/pkg/warewulfd/system.go
internal/pkg/warewulfd/util.go
internal/pkg/warewulfd/warewulfd.go

This PR causes the Warewulf daemon to build or update a given overlay if it does not exist or if anything was changed.
Resolves: #146

Update or build overlays on demand

---

internal/app/wwctl/profile/set/main.go
internal/app/wwctl/profile/set/root.go
internal/pkg/node/constructors.go

Allow `--discoverable` option to be set via profiles

---

Makefile

By default `wwclient` will be installed for all system-overlays by `make install` or `make install_wwclient`.
A specific overlay can be targeted by providing the variable `OVERLAY_DIR`.
example for the system-overlay `test`:
```sh
sudo make OVERLAY_DIR=/var/warewulf/overlays/system/test install_wwclient
```
NOTE: the path must _not_ be suffixed with a `/`!
closes #217

install `wwclient` for all system overlays

---

internal/pkg/kernel/kernel.go

Better logic to locate kernels

---

Makefile

Some minor cleanups to the makefile and build output

Cleanups to makefile so we don't pollute our source dirs

---

etc/ipxe/big_image.ipxe
etc/ipxe/default.ipxe

This is a commit for @griznog's suggestion in #222.

Implement fix for #222 (thanks Griznog!)

---

internal/app/wwctl/container/imprt/main.go
internal/pkg/kernel/kernel.go

- fixed kernel import from container
- need valid url or dir to import something

fixups for kernel import

---

Makefile
internal/pkg/overlay/funcmap.go
overlays/wwinit/etc/ssh/ssh_host_dsa_key.pub.ww
overlays/wwinit/etc/ssh/ssh_host_dsa_key.ww
overlays/wwinit/etc/ssh/ssh_host_ecdsa_key.pub.ww
overlays/wwinit/etc/ssh/ssh_host_ecdsa_key.ww
overlays/wwinit/etc/ssh/ssh_host_ed25519_key.pub.ww
overlays/wwinit/etc/ssh/ssh_host_ed25519_key.ww
overlays/wwinit/etc/ssh/ssh_host_rsa_key.pub.ww
overlays/wwinit/etc/ssh/ssh_host_rsa_key.ww
overlays/wwinit/etc/sysconfig/network-scripts/ifcfg-default.ww
overlays/wwinit/etc/warewulf/warewulf.conf.ww

There are a number of fixes necessary after merging the relocation features

Various relocation fixes

---

etc/warewulf.conf

nfs mount option must be defaults

---

internal/app/wwctl/overlay/mkdir/mkdir_test.go
internal/app/wwctl/overlay/mkdir/root.go

Added argument testing around this.

Fix wwctl overlay mkdir #248.

---

overlays/wwinit/etc/issue.ww

adds some information about the node before login

add some eyecandy

---

internal/pkg/overlay/overlay.go
overlays/wwinit/etc/issue.ww

Added some more values for templating the .ww files and /etc/issue.ww will 
so show more stuff

added more values for templating .ww files in overlays

---

Makefile
internal/pkg/kernel/kernel.go

Fix kernel imports and 4.2.x branch releases

---

etc/ipxe/default.ipxe
internal/pkg/node/constructors.go
internal/pkg/warewulfd/container.go
internal/pkg/warewulfd/kernel.go
internal/pkg/warewulfd/kmods.go
internal/pkg/warewulfd/runtime.go
internal/pkg/warewulfd/system.go

Minor fixups as I'm doing testing.

Minor fixups

---

internal/app/wwclient/root.go
internal/app/wwctl/node/status/main.go
overlays/wwinit/etc/issue.ww

Minor fixes to wwclient and node status output.

wwclient fixes

---

internal/app/wwctl/node/set/main.go
internal/app/wwctl/profile/set/main.go
internal/pkg/node/constructors.go
internal/pkg/node/datastructure.go
internal/pkg/node/methods.go

Fixes #292 and includes some network configuration optimizations.

Discoverable and network fixes

---

internal/app/wwctl/profile/set/main.go
internal/app/wwctl/profile/set/root.go
internal/pkg/node/constructors.go

IP address
MAC address
Asset Tag
IP and MAC are unique to each node. It seems like asset tag should be unique as well.

Remove unique settings from profile set. Warn if set in the node DB.

---

internal/pkg/kernel/kernel.go

added search path for kernel to allow arch users to utilize the `` wwctl kernel import `` functionality

added kernel search path for arch compatibility

---

internal/app/wwctl/container/exec/child/main.go
internal/app/wwctl/container/exec/child/non-Linux.go
internal/app/wwctl/container/exec/child/root.go
internal/app/wwctl/container/exec/root.go

This reverts commit 30bc445a89288a0837a271b6309cc19e852c7a92 from #318.

Revert "removed unused container child"

---

containers/Docker/centos-8
containers/Docker/rocky-8
internal/app/wwctl/container/exec/child/main.go
internal/app/wwctl/container/exec/child/non-Linux.go
internal/app/wwctl/container/exec/child/root.go
internal/app/wwctl/container/exec/root.go

Minor fixes to container definitions

Container fixes

---

Makefile
warewulf.spec.in

Thank you @truatpasteurdotfr for catching this (ref #305)

Fixing RPM build error caused by #301

---

internal/pkg/node/constructors.go
internal/pkg/overlay/overlay.go

* if the template provides multiple files, the base file won't be written
* add the255.255.255.0 as default netmask to every interface

Remove-base-template

---

.github/workflows/lint.yaml

Maybe get past the linter errors.

Pin go to 1.17

---

Makefile
internal/app/wwctl/container/exec/child/main.go
internal/app/wwctl/container/exec/main.go

Local linter is in sync with github linter and fixed linting

Local-lint-fix

---

.github/workflows/lint.yaml
Makefile

golang-lintci v.1.45.2 + fix yaml syntax

---

internal/pkg/node/constructors.go
internal/pkg/node/methods.go
internal/pkg/node/modifiers.go

Fixes #365. Gets unit tests passing again.

Fix 365. Nil checks around pointers in nodes.conf.

---

.github/workflows/test.yml
internal/pkg/node/util_test.go

I think I need to open a PR to trigger tests (?)
We'll see if they run.

Vet and test in CI.

---

overlays/generic/etc/passwd.ww
overlays/wwinit/etc/issue.ww
overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww
overlays/wwinit/etc/systemd/system/wwclient.service
overlays/wwinit/etc/wicked/ifconfig/ifcfg.xml.ww

smaller chnages for smoother overlays

various fixes in overlays

---

internal/pkg/kernel/kernel.go

fix typo in kernel import

---

Makefile

evil Makefile bash magic to trick the tests to find warewulf.conf

Makefile update for test coverage

---

go.mod
internal/pkg/node/modifiers.go
internal/pkg/node/node_test.go

Fixes https://github.com/hpcng/warewulf/issues/366
The CI build will fail since I did not update the failing test yet.

Nil check node configuration pointers.

---

internal/pkg/node/constructors.go
internal/pkg/node/methods.go
internal/pkg/node/modifiers.go

fixup profile handling so that tags of netdevs are correctly profilerated

profile fixup

---

warewulf.spec.in

suse specifc changes for openbuild service

fixed up spec file

---

internal/app/wwctl/node/list/main.go
internal/app/wwctl/profile/list/main.go

Some minor UI cleanups around boolean print consistency (e.g. IPMIWrite and Discoverable).

Align boolean prints

---

internal/pkg/node/methods.go

Fix removal of values

---

internal/app/wwctl/node/set/main.go

Fix wwct node set profile for single profile

---

.github/workflows/releasebuild.yml

Update the upload-artifacts and download-artifacts version
Signed-off-by: Michael L. Young <myoung@ciq.co>

Adjust release build artifacts upload to handle pre-releases

---

internal/pkg/node/constructors.go

backported :-)
fix #468 in branch main

fix nil map for networks

---

.gitignore
Makefile

- Add .dist to gitignore
- Purge emacs temporary files from dist

Small dist cleanup

---

Makefile
docs/man/man5/nodes.conf.5
docs/man/man5/warewulf.conf.5
etc/warewulf.conf
internal/pkg/warewulfconf/datastructure.go
warewulf.spec.in

This is a draft / work-in-progress PR for new `warewulf.conf` and `nodes.conf` man pages. Future commits may be reorganized / squashed as work is done.
Addresses #510

new man pages for warewulf.conf and nodes.conf

---

internal/pkg/overlay/overlay.go

Fix a typo in symlink wwbackup implementation

---

internal/app/wwctl/configure/hostfile/main.go
internal/app/wwctl/configure/hostfile/root.go
internal/app/wwctl/configure/main.go
internal/app/wwctl/configure/root.go
internal/pkg/configure/hostfile.go
internal/pkg/overlay/overlay.go

readded configure hostfile command

---

internal/pkg/api/container/container.go
internal/pkg/container/util.go

remove also the container image on delete

---

internal/app/wwctl/overlay/show/main.go

Error logging for overlay show rendering incorrectly checked the overlay name rather than the path to the file. It also used wwlog (which goes to stderr) to output the render. This commit replaces explicit args[] references with their named equivalents from earlier in the function, correcting those references along the way, and outputs the final render with fmt.Print.
This commit also causes the ERROR condition to Exit(), similarly to other ERROR conditions in this function.

Fix argument handling for overlay show rendering

---

API.md
CHANGELOG.md

Docs for API. Do need to spend more time with this.

Add API.md and update CHANGELOG.md for the API.

---

internal/pkg/api/node/list.go
internal/pkg/node/transformers.go

- create memory for nettags
- use tag instead of nettag
close #565

fix add of new nettags

---

internal/pkg/overlay/overlay.go

Fix overlay error typos

---

overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww

Configure interface type and name in ifcfg

---

internal/pkg/api/container/container.go

Fixes segault if there is a container chroot without image

react on the error accordingly

---

Makefile
staticfiles/README-ipxe.md
staticfiles/README.md

Building off the work in #581, add additional detail to the staticfiles README, and install an iPXE README alongside the iPXE files in their final location.
Closes #189

Additions to and install staticfiles README

---

CONTRIBUTORS.md

Added myself and Brian to CONTRIBUTORS

---

CHANGELOG.md

Added a missing PR tag to CHANGELOG

---

CHANGELOG.md
docs/man/man5/defaults.conf.5

New man page: defaults.conf

---

docs/man/man5/nodes.conf.5
docs/man/man5/warewulf.conf.5

Capitalize Warewulf in man pages where appropriate

---

CHANGELOG.md
overlays/debug/warewulf/template-variables.md.ww

A new debug overlay template serves as an example of how to access all template variables which can also be rendered against any node to display all template variable values.

New debug overlay with template

---

overlays/debug/warewulf/template-variables.md.ww

Removed whitespace damage from new debug template

---

.github/workflows/documentation.yml
.github/workflows/lint.yaml
.github/workflows/releasebuild.yml
.github/workflows/test.yml
ci/mockbuild.sh

* Upload SRPMs that are created
* Update actions/checkout to v3
Closes #614
Signed-off-by: Michael L. Young <myoung@ciq.co>

Add SRPM Artifact To Releases

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Templates for GitHub issues and pull requests

---

internal/pkg/node/methods.go

GetB must not ignore altvalue

---

internal/pkg/container/kernel.go

Resolves the kernel version, if e.g the symlink `boot` was found in the first place,

resolve symlink for kernel version

---

Makefile

fix permission of config.ww

---

include/systemd/warewulfd.service.in

use always @BINDIR@

---

internal/pkg/api/container/container.go

container show will only show valid containers

---

internal/pkg/api/node/list.go

sort netnames for node list

---

internal/pkg/container/syncuids.go

- Rename some internal variables to make the function easier to follow
- Refactor some code to make it simpler
- Remove some commented-out code
- Fix an error message
- Fixes #650

Refactor some variables in syncuser and correct error message

---

userdocs/contents/containers.rst
userdocs/contributing/development-environment-kvm.rst
userdocs/contributing/development-environment-vbox.rst
userdocs/debian/debian.md

Capitalize Warewulf in userdocs where appropriate

---

userdocs/contents/containers.rst
userdocs/contents/initialization.rst
userdocs/contents/installation.rst
userdocs/contents/ipmi.rst
userdocs/contents/kernel.rst
userdocs/contents/nodeconfig.rst
userdocs/contents/overlays.rst
userdocs/contents/profiles.rst

Console-style code-block and remove sudo

---

userdocs/contents/containers.rst
userdocs/contents/initialization.rst
userdocs/contents/installation.rst
userdocs/contents/ipmi.rst
userdocs/contents/overlays.rst
userdocs/contents/templating.rst
userdocs/quickstart/el7.rst

Fix accidental userdocs italics

---

internal/app/wwctl/overlay/build/main.go

build host overlay only if requested

---

internal/app/wwctl/overlay/edit/main.go
internal/app/wwctl/overlay/edit/root.go
internal/app/wwctl/overlay/imprt/root.go

If a new file doesn't have the .ww suffix, the output is a bit scary, just show this messages on verbose mode

make output less scary for new files

---

internal/pkg/batch/batch.go
internal/pkg/batch/batch_test.go

A first step in an attempt to generate automated tests for full coverage of internal/pkg. This PR tests the batch package.

Automated tests for batch

---

.gitattributes

use uinion strategy for CHANGELOG.md as there lines should be uniq

use union strategy for CHANGELOG.md

---

userdocs/contributing/debugging.rst
userdocs/index.rst

I wrote some documentation about how to debug warewulf using delve, particularly coupled with the test suite.

Add a userdocs page for using delve to debug tests

---

internal/app/wwctl/profile/add/main.go

correct behavior of profile add to yes flag

---

CHANGELOG.md
internal/app/wwctl/container/list/main_test.go
internal/app/wwctl/profile/add/main.go
internal/app/wwctl/profile/add/main_test.go
internal/app/wwctl/profile/add/root.go
internal/pkg/api/profile/profile.go
internal/pkg/node/constructors.go
internal/pkg/node/modifiers.go

Refactor `profile add` to make it like `node add
- Fixes #658 #659 

Refactor `profile add` to make it like `node add`

---

.github/workflows/changelog-enforcer.yml

* https://github.com/marketplace/actions/changelog-enforcer
* https://dangoslen.medium.com/enforcing-a-changelog-with-github-actions-279119ed4182
Closes #278

Enable the changelog enforcer

---

docs/man/man5/warewulf.conf.5
userdocs/contents/configuration.rst

Additional documentation for warewulf.conf:warewulf.secure

---

CHANGELOG.md
pkg/hostlist/hostlist_test.go
userdocs/contents/wwctl.rst
userdocs/index.rst

Added this to a new top-level page for wwctl
Closes #611

Documentation and tests for hostlist syntax

---

CHANGELOG.md
userdocs/quickstart/el9.rst

Quickstart Guide for EL9

---

CHANGELOG.md
userdocs/contributing/development-environment-vagrant.rst
userdocs/index.rst

New documentation for development environment (Vagrant)

New documentation for development environment (Vagrant)

---

CHANGELOG.md
overlays/wwinit/init

/sbin/reboot needs systemd to be running, so reboot the hard^W easy way

reboot also without systemd

---

CONTRIBUTORS.md
README.md
warewulf.spec.in

Update ciq.com URLs

---

ipxe-update.sh

add support to install efi and bios from system path.
- Fixes #689 

add support to install efi and bios from system path

---

CHANGELOG.md

Just updating the CHANGELOG to reflect the changes for #852, #876, #883, #896, and #903.

Update CHANGELOG for changes to overlay names

---

LICENSE.md

Fixes some formatting issues with LICENSE.md and adds attribution for RESF in anticipation of becoming an RESF project.

Update LICENSE.md for formatting and contributors

---

CHANGELOG.md
internal/pkg/node/constructors.go
internal/pkg/node/constuctors_test.go

return the primary network interface for discoverd

---

CHANGELOG.md
overlays/wwinit/warewulf/init.d/50-ipmi

only write ipmi of IpmiWrite is true

---

CHANGELOG.md
internal/app/wwctl/node/set/main_test.go
internal/pkg/node/flags.go

added also a test for this
close #947

mtu can be set via command line

---

CHANGELOG.md
internal/pkg/api/container/container.go

no error if images for containers don't exist

---

CHANGELOG.md
internal/app/wwctl/node/set/main_test.go
internal/pkg/node/transformers.go

check if entry has real value in recursive getter

---

.github/workflows/changelog-enforcer.yml

Skipping changelog enforcement for PRs with one of these labels:
refactor, testing, build, project.
Such labels likely indicate a non-user-visible change which need not be reflected in the changelog. (Of course, a changelog entry may still be made if appropriate, even if not required by the enforcer.)

Skip changelog enforcement for certain labels

---

.github/workflows/documentation.yml

- Prevent attempts to publish docs when userdocs has not changed.
- Publish docs pushed to release branches

Update documentation workflow

---

userdocs/contents/introduction.rst

Small typo correction SuSE -> SUSE

Typo correction SuSE -> SUSE

---

CONTRIBUTORS.md
userdocs/contents/setup.rst

Typo in setup.rst (then vs. than)

---

CHANGELOG.md
warewulf.spec.in

- Minor fixes to enable building rpms for Fedora
- Updating Changelog
Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
- Fixes #

fedora specfile fixes

---

CHANGELOG.md
internal/pkg/util/util.go

import symlinked /bin/sh

---

CHANGELOG.md
internal/pkg/container/syncuids.go
internal/pkg/container/syncuids_test.go

added a test for malformed passwd and fixed the panic
close #527

don't panic on malformed passwd

---

CHANGELOG.md
internal/app/wwctl/container/imprt/root.go
internal/pkg/api/container/container.go

Fix a bug when replacing existing containers will generate an error
- Fixes #474
Before:
After:

fix a bug when replacing existing containers will generate an error

---

userdocs/contributing/contributing.rst

Update Slack invite for Warewulf Slack

---

.github/workflows/documentation.yml

Update location where the generated userdocs are deposited.

Update website repo URL

---

CHANGELOG.md
internal/pkg/node/constuctors_test.go
internal/pkg/node/methods.go
tools.go

If a node contains several profiles and these profiles have
overlays attached, these profiles are now merged. Overlays
can't be excluded as this can not be displayed to the user
close #885

overlays from different profiles are merged

---

CHANGELOG.md
internal/app/wwctl/kernel/imprt/main.go
internal/pkg/kernel/kernel.go
internal/pkg/kernel/kernel_test.go
internal/pkg/overlay/overlay_test.go
internal/pkg/util/cpio.go
internal/pkg/util/util.go

- added test and refactored kernel.Build
- fixed kmod creation
close #836

Fix empty kernel modules and drivers

---

CHANGELOG.md
etc/ipxe/localdisk.ipxe

- An ipxe script to boot from local disk.
- Update changelog.
Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
- Fixes #

Boot from disk via ipxe.

---

CHANGELOG.md
internal/app/wwctl/node/edit/main.go
internal/app/wwctl/node/edit/root.go
internal/app/wwctl/profile/edit/main.go
internal/pkg/api/util/util.go

Fix showing error when editing node.
- Fixes #1024
- Fixes #1057

Fix error when editing node

---

CHANGELOG.md
internal/pkg/config/root.go

Fix the issue that configuration expects CIDR address. 
- Fixes #1016

fix the bug that configuration expects CIDR format

---

CHANGELOG.md
internal/app/wwctl/node/set/main_test.go
internal/pkg/node/flags.go

added check if commas can be set

---

CHANGELOG.md
internal/app/wwctl/container/syncuser/main.go
internal/app/wwctl/container/syncuser/root.go

add container build after container sync
- Fixes #509

add container build after container sync

---

CHANGELOG.md
etc/nodes.conf
etc/warewulf.conf
internal/app/wwctl/container/list/main_test.go
internal/app/wwctl/node/add/main_test.go
internal/app/wwctl/node/list/main_test.go
internal/app/wwctl/node/set/main_test.go
internal/app/wwctl/overlay/imprt/main_test.go
internal/app/wwctl/overlay/show/main_test.go
internal/app/wwctl/profile/add/main_test.go
internal/app/wwctl/profile/list/main_test.go
internal/pkg/config/root_test.go
internal/pkg/node/hash_test.go
internal/pkg/node/node_test.go
internal/pkg/overlay/funcmap_test.go
internal/pkg/testenv/testenv.go
internal/pkg/testenv/testenv_test.go
internal/pkg/warewulfd/provision_test.go
userdocs/quickstart/suse15.rst

Internal version update is necessary as new structures were added,
most obviously the disk, partitions and file system structures.
Old configurations will work as expected.
- Closes #966

updated WW_INTERNAL to 45 for 4.5.x release

---

CONTRIBUTORS.md
userdocs/contents/disks.rst

Rebase and refactor of PR #1077

Henkela disks docs

---

CHANGELOG.md
userdocs/contents/nodeconfig.rst
userdocs/contents/setup.rst

- Added documentation about of how to configure warewulf with 
multiple networks

Documentation for mulitple networks

---

CHANGELOG.md
userdocs/contents/dnsmasq.rst

updated dnsmasq documentation with installation instructions

Document installation instructions for dnsmasq

---

CHANGELOG.md
overlays/wwinit/rootfs/etc/systemd/system/ww4-disks.target.ww
overlays/wwinit/rootfs/etc/systemd/system/ww4-mounts.ww

Fix mounting local partitions into sub directoies.
- Fixes #1073

Make mounting into sub-directoies work

---

CHANGELOG.md
internal/app/wwctl/node/list/main_test.go
internal/pkg/node/constructors.go

Fix panic when node has no profile but network does

---

.github/actions/prepare/action.yml
CHANGELOG.md
userdocs/contents/setup.rst
warewulf.spec.in

Update CHANGELOG for v4.5.0

---

userdocs/index.rst
userdocs/quickstart/el7.rst

Restore el7 quickstart

---

.github/workflows/check.yml
CHANGELOG.md
Tools.mk
go.mod

Several dependabot created PRs require minimum golang version of 1.19
```
Run make vet
fatal: No names found, cannot describe anything.
go vet ./...
Error: vendor/github.com/klauspost/compress/zstd/dict.go:[4](https://github.com/warewulf/warewulf/actions/runs/7999361562/job/21847043335?pr=1103#step:4:5)79:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: vendor/github.com/klauspost/compress/zstd/dict.go:490:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: vendor/github.com/klauspost/compress/zstd/dict.go:491:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: …
```

upgrade minimum golang version to 1.19 and golangci-lint version to 1.56.2

---

CHANGELOG.md
internal/app/wwctl/container/delete/root.go
internal/app/wwctl/container/imprt/root.go
internal/app/wwctl/container/shell/root.go
internal/app/wwctl/container/show/root.go
internal/app/wwctl/kernel/delete/root.go
internal/app/wwctl/kernel/imprt/root.go
internal/app/wwctl/node/add/root.go
internal/app/wwctl/node/delete/root.go
internal/app/wwctl/node/set/root.go
internal/app/wwctl/overlay/create/root.go
internal/app/wwctl/overlay/delete/root.go
internal/app/wwctl/profile/add/root.go
internal/app/wwctl/profile/delete/root.go
internal/app/wwctl/profile/set/root.go

just for convinience
- Closes: #1123

added more aliases for wwctl commands

---

CHANGELOG.md
warewulf.spec.in

change ipxe location for SUSE based distros at build time

---

.github/workflows/check.yml

Run tests against v4.5.x branch (and other release branches).

Run tests against PRs to v4.*.x branches

---

CHANGELOG.md
Makefile
Variables.mk
scripts/get-version.sh
scripts/rpm-release.sh
scripts/rpm-version.sh

Calculate VERSION and RELEASE dynamically from git. Prior to this, each was set statically in the source tree.

Calculate VERSION and RELEASE dynamically from git

---

CHANGELOG.md

Update the changelog in anticipation of v4.5.1.

Update CHANGELOG to anticipate v4.5.1

---

CHANGELOG.md

Just updating the changelog to indicate the v4.5.1 release.
Closes #1172

v4.5.1 release

---

userdocs/contents/configuration.rst
userdocs/contents/installation.rst
userdocs/contributing/development-environment-vagrant.rst
userdocs/quickstart/debian12.rst
userdocs/quickstart/el.rst

Updates docs to refer to v4.5.1 release when appropriate.

Update docs for v4.5.1 release

---

CHANGELOG.md
userdocs/contents/profiles.rst

- **Replace --addprofile with --profile**
- **Updating CHANGELOG**

doc fix 1085

---

CHANGELOG.md
etc/warewulf.conf
internal/app/wwctl/configure/root.go
internal/app/wwctl/configure/ssh/main.go
internal/app/wwctl/configure/ssh/root.go
internal/pkg/config/root.go
internal/pkg/config/ssh.go
internal/pkg/configure/ssh.go
internal/pkg/overlay/datastructure.go
overlays/debug/rootfs/warewulf/template-variables.md.ww
overlays/host/rootfs/etc/profile.d/ssh_setup.csh.ww
overlays/host/rootfs/etc/profile.d/ssh_setup.sh.ww
userdocs/contents/configuration.rst

Was a low hanging fruit
- Close #1185

allow the user to specify ssh key types

---

CHANGELOG.md
internal/app/wwctl/configure/main.go

Call SSH(keys) on configure --all

---

.github/actions/prepare/action.yml
CHANGELOG.md

Reverts warewulf/warewulf#1243

Revert "run go mod tidy after go mod vendor"

---

.github/actions/rpm/action.yml
CHANGELOG.md

caused by appended newline
- Fixes #
my branch succeeded on the patch
https://github.com/JasonYangShadow/warewulf/actions/runs/9476358087

fix nightly build invalid format issue

---

CHANGELOG.md
internal/app/wwctl/container/exec/child/main.go

- **be more verbose on container exec**

be more verbose on container exec

---

CHANGELOG.md
internal/app/wwctl/overlay/chmod/root.go
internal/app/wwctl/overlay/chown/root.go
internal/app/wwctl/overlay/delete/root.go
internal/app/wwctl/overlay/edit/root.go

added completion to overlay chmod/chown/delete/edit

---

CHANGELOG.md
etc/grub/grub.cfg.ww
etc/ipxe/default.ipxe
etc/ipxe/dracut.ipxe

Check if container is defined during boot process and give proper error otherwise
Fixed version of #1275

Check for empty container var 

---

userdocs/contents/disks.rst

updated documenation regarding fswipe

---

CHANGELOG.md
Makefile
Variables.mk
etc/logrotate.d/warewulfd.conf
warewulf.spec.in

Add logrotate support
- Closes #1311

logrotate support

---

CHANGELOG.md
userdocs/contents/security.rst

Update SELinux documentation to reference an example node image.

Update selinux documentation to reference an example

---

CHANGELOG.md
internal/pkg/configure/dhcp.go
internal/pkg/configure/hostfile.go
internal/pkg/configure/ssh.go
internal/pkg/configure/tftp.go

refine `wwctl configure` error hanlding.
- Fixes #1273

refine `wwctl configure` error handling

---

CONTRIBUTING.md
MAINTAINING.md

Additional rules for adding TSC members and selecting the TSC chair.

Add rules for TSC member and chair selection

---

CHANGELOG.md
internal/pkg/container/syncuids.go

Additional guidance when syncuser conflicts

---

CHANGELOG.md
CONTRIBUTORS.md
overlays/wwinit/rootfs/init

Reverts warewulf/warewulf#822
#1401 is preferred.

Revert "Init rootfs fixes"

---

CHANGELOG.md
go.mod
go.sum
internal/pkg/kernel/kernel.go
internal/pkg/kernel/kernel_test.go

fix autodetected kernel sorting
- Fixes #1332

fix autodetected kernel sorting

---

CHANGELOG.md
internal/app/wwctl/container/list/main.go
internal/app/wwctl/container/list/main_test.go
internal/app/wwctl/container/rename/main_test.go
internal/app/wwctl/helper/printhelper.go
internal/app/wwctl/node/list/main.go
internal/app/wwctl/node/list/main_test.go
internal/app/wwctl/profile/list/main.go
internal/app/wwctl/profile/list/main_test.go

Fix excessive line spacing issue when listing nodes
- Fixes #1241

Fix excessive line spacing issue when listing nodes

---

CHANGELOG.md
userdocs/contents/troubleshooting.rst
userdocs/index.rst

New troubleshooting guide to capture some practices I've gathered during boot development.

New troubleshooting guide

---

CHANGELOG.md
Makefile
internal/app/wwctl/container/list/main.go
internal/app/wwctl/container/list/main_test.go
internal/app/wwctl/container/list/root.go
internal/pkg/api/container/container.go
internal/pkg/testenv/testenv.go

Fix panic when getting a long container list before building the container

---

CHANGELOG.md
internal/app/wwctl/container/imprt/root.go
userdocs/quickstart/el.rst

Some fixes for the Rocky / EL quickstart.
- Closes #1179

Fixes for EL quickstart

---

CHANGELOG.md
userdocs/contents/containers.rst

Add workaround documentation for importing containers with sockets

---

CHANGELOG.md
userdocs/contents/boot-management.rst
userdocs/contents/containers.rst
userdocs/contents/disks.rst

New documentation for building iPXE locally.
- Fixes #1114

Building ipxe locally

---

CHANGELOG.md
userdocs/contents/disks.rst

Document that ignition is not available for Rocky Linux 8

---

overlays/wwinit/rootfs/init

Fixes a regression introduced in #1401.
Found by Ian Kaufman and the fine folks in the new `#on-debian` Slack channel.

Fix a missing string quote

---

CHANGELOG.md
internal/pkg/api/node/node.go

fix issue that pattern matching broken on node set
- Fixes #964
```
[root@localhost warewulf]# wwctl node add node[00-09]
Added node: node00
Added node: node01
Added node: node02
Added node: node03
Added node: node04
Added node: node05
Added node: node06
Added node: node07
Added node: node08
Added node: node09
[root@localhost warewulf]# wwctl node set --profile compute node[00-09]
? Are you sure you want to modify 10 nodes(s)?
[root@localhost warewulf]# wwctl node add n[00-11].example.com
Added node: n00.example.com
Added node: n01.example.com
Added node: n02.example.com
Added node: n03.example.com
Added node: n04.example.com
Added node: n05.example.com
Added node: n06.example.com
Added node: n07.example.com
Added node: …
```

fix issue that pattern matching broken on node set

---

internal/app/wwctl/node/list/main_test.go
internal/pkg/node/list.go
internal/pkg/node/methods.go

- Refactor field reflection for clarity
- Update tests for clarity
- Fixes #1472

Fix boolean pointer handling

---

internal/pkg/warewulfd/daemon.go

Removes dead code following #1229.

Remove deadcode from warewulfd

---

.github/workflows/check.yml

Check for dead code as part of the GitHub test suite.
- Fixes #1502 

Add deadcode to the github test suite

---

internal/pkg/node/datastructure.go

Remove an apparently unused IsZero function.
- Fixes #1509

Remove unused IsZero function

---

CHANGELOG.md
internal/app/wwctl/container/exec/child/main.go
internal/app/wwctl/kernel/imprt/main.go
internal/app/wwctl/node/edit/main.go
internal/app/wwctl/overlay/delete/main.go
internal/app/wwctl/overlay/imprt/main.go
internal/app/wwctl/overlay/list/main.go
internal/app/wwctl/profile/delete/main.go
internal/app/wwctl/server/root.go
internal/pkg/api/container/container.go
internal/pkg/api/node/add.go
internal/pkg/api/node/delete.go
internal/pkg/api/node/edit.go
internal/pkg/api/profile/add.go
internal/pkg/api/profile/delete.go
internal/pkg/api/profile/edit.go
internal/pkg/api/profile/set.go
internal/pkg/config/root.go
internal/pkg/configure/dhcp.go
internal/pkg/configure/hostfile.go
internal/pkg/configure/nfs.go
internal/pkg/configure/ssh.go
internal/pkg/container/build.go
internal/pkg/kernel/kernel.go
internal/pkg/overlay/overlay.go
internal/pkg/util/util.go
internal/pkg/warewulfd/daemon.go
internal/pkg/warewulfd/nodedb.go
internal/pkg/warewulfd/status.go
internal/pkg/warewulfd/warewulfd.go

replaced deprecated errors.Wrapf with fmt.Errorf

replaced errors.Wrap with fmt.Errorf

---

CHANGELOG.md
overlays/wwinit/rootfs/warewulf/init.d/50-ipmi

don't update ipmi if there is no password

---

internal/app/wwctl/node/list/main_test.go
internal/app/wwctl/profile/list/main_test.go

Restore skipped tests

---

internal/app/wwctl/node/list/main_test.go

fix test suite build failure in current main branch (raised by this merge https://github.com/warewulf/warewulf/commit/e6f5c63c21f62e24113b33d1c81c3aa11890b708)
- Fixes #

hotfix failure test suite

---

internal/app/wwctl/node/set/main_test.go

if newely added tests after refactor

fix tests after refactor

---

CHANGELOG.md
internal/app/wwctl/node/set/main_test.go
internal/pkg/api/node/set.go

 Fix panic when adding tag with existing netdev

---

.github/workflows/check.yml

Temporary fix for #1571
- #1571

Disable deadcode check for previous golang versions

---

CHANGELOG.md
go.mod
go.sum

Addresses https://github.com/warewulf/warewulf/security/dependabot/64

Update github.com/opencontainers/runc to 1.1.14

---

internal/pkg/node/fields.go

Fix a panic introduced by #1598

---

internal/pkg/node/fields_test.go
internal/pkg/node/ignition.go
internal/pkg/overlay/config.go
internal/pkg/overlay/overlay.go
internal/pkg/overlay/overlay_test.go

A few linting issues that were called out by vscode.

Linting fixes called-out by vscode

---

CHANGELOG.md
internal/app/wwctl/root.go
internal/app/wwctl/upgrade/config/cobra.go
internal/app/wwctl/upgrade/nodes/cobra.go

Respect WAREWULFCONF and `--warewulfconf` during `wwctl upgrade`.
- Fixes #1658

wwctl upgrade config path

---

CHANGELOG.md
warewulf.spec.in

Recommend installing ipmitool with Warewulf package

---

userdocs/contents/configuration.rst

Document setting the wwclient port

---

CHANGELOG.md
internal/pkg/overlay/config.go
warewulf.spec.in

Create the site overlay directory with the RPM, but also create it if it doesn't exist.
-Fixes: #1690

Create site overlay directory

---

.gitattributes
CHANGELOG.md
Makefile
warewulf.spec.in

- explicitly indicate what to include in dist
- prevent duplication of files in specfile

Simplify Makefile and spec

---

CHANGELOG.md
internal/app/wwctl/completions/completions.go
internal/app/wwctl/profile/delete/root.go
internal/app/wwctl/profile/list/root.go
internal/app/wwctl/profile/set/root.go

add completion for profile list

---

CHANGELOG.md
userdocs/contents/configuration.rst

Document `warewulf.conf:dhcp.template`

---

CHANGELOG.md
internal/app/wwctl/node/export/main.go
internal/pkg/api/node/edit.go

Updated `wwctl node export` to include node IDs

---

internal/app/wwctl/completions/completions.go
internal/app/wwctl/node/add/root.go
internal/app/wwctl/node/set/root.go
internal/app/wwctl/profile/add/root.go
internal/app/wwctl/profile/set/root.go

Fix image completion

---

CHANGELOG.md
internal/app/wwctl/image/exec/child/main.go
userdocs/contents/images.rst

Update PS1 during `wwctl image shell` to include working directory

---

CHANGELOG.md
internal/app/wwclient/root.go

set IdleConnTimeout wwclient to 2*UpdateInterval

---

userdocs/getting-started/debian-quickstart.rst

minor typo debian-quickstart.rst

---

CHANGELOG.md
internal/pkg/warewulfd/nodedb.go
internal/pkg/warewulfd/nodedb_test.go

- Fixes: #1817
Add panicing test to confirm

Allow discover of nodes with network only in profile

---

CHANGELOG.md
internal/app/wwctl/image/rename/main_test.go
internal/pkg/api/image/image.go

Update nodes and profiles when renaming an image.
- Fixes: #1637

Update nodes and profiles when renaming an image

---

userdocs/server/configuration.rst

Add documentation for logging configuration.

Add logging configuration documentation

---

Makefile
go.mod
go.sum
internal/pkg/api/image/image.go

- Fix `make deadcode` to properly fail GitHub checks
- Resolve "dead" code by refactoring other code to use it

Address unhandled deadcode issues

---

userdocs/overlays/overlays.rst
userdocs/release/v4.6.0.rst

Misc. documentation typo fixes.

Misc. documentation typo fixes

---

CHANGELOG.md
include/sos/warewulf.py

The PR modified the `wwctl container list` command to use -l to gather more information when run.

Updated Warewulf SOS Plugin

---

CHANGELOG.md
internal/pkg/warewulfd/api/node.go

Fail API node add if node already exists. Client gets a 400.
Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
- Fixes #

Fail API add node if node exists

---

CHANGELOG.md
overlays/wwinit/rootfs/warewulf/init.d/50-ipmi

Commands were being echo'd rather than run.
- Closed: #1892

Fixed IPMI VLAN configuration

---

internal/pkg/node/datastructure.go
internal/pkg/node/fields.go
internal/pkg/node/fields_test.go

Improves output for boolean-pointer fields.

Read field names from field tags

---

.github/releases/v4.6.4.md
CHANGELOG.md
userdocs/getting-started/debian-quickstart.rst
userdocs/getting-started/el-quickstart.rst
userdocs/release/v4.6.4.rst
userdocs/server/bootloaders.rst
userdocs/server/installation.rst

Preparation for the v4.6.4 release.

v4.6.4 release updates
